### ISSUE TITLE
(vscode) If Format on save option is enabled, the file ends in an unsaved state after the formatting operation

### ISSUE THREAD

**Issue by ajboni** [Scony/godot-gdscript-toolkit#107]
If VSCode "Format on save" option is enabled, the file ends in an unsaved state after the formatting operation. It needs two saves.

1. modify contents
2. CTRL + S
3. Formatting gets applied
4. File is not saved.
2. CTRL + S again: File is saved (because there is no formatting)

It might be related to #80

**Comment by Skuriles** [comment]
The most annoying thing about that is when you save multiple files at once all opened unsaved filed except the current selected one remain unsaved. No matter how often you hit the save all button. 

To reproduce:
Edit 2 files
Press save all in VS Code
Current one is saved, than formatted => remains unsaved
All others are formatted => remain unsaved
Press again current one is saved, all others are unsaved

**Comment by Scony** [comment]
@Razoric480
