### ISSUE TITLE
Can gdformat provide a switch for the indent type?

### ISSUE THREAD

**Issue by Centauria** [Scony/godot-gdscript-toolkit#110]
Now `gdformat` can only use Tab for indent.
It will sure be an honor if it can let us choose the indent type, such as 2 spaces, 4 spaces, n spaces, and Tab itself.

**Comment by Scony** [comment]
as per https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#formatting `gdformat` takes a conservative approach to use tabs only. I'm not sure if space indents should be supported at all. What would be the motivation for that (apart from `tabs vs spaces` matter)?

**Comment by Centauria** [comment]
OK, if the godot official document recommends using Tab, I have nothing to say.
I just get used to the space indent and set all my editors to transfer tab into spaces. So it often get an indent error when I forget to reformat the code.

**Comment by Scony** [comment]
I had the same habits, but eventually, I've configured my env to use tabs, and ever since all is fine :)

**Comment by idraper** [comment]
@Scony it is now possible to configure the editor to indent via spaces - it would be nice if we could configure the formatter to do the same

<img width="674" alt="image" src="https://github.com/Scony/godot-gdscript-toolkit/assets/32877813/dc169c3f-7784-481d-be9d-52b943056eed">

**Comment by Scony** [comment]
@idraper in that case a switch make actually make sense

**Comment by Scony** [comment]
Fixed in 8b66d13
