### ISSUE TITLE
The vs code gdscript format extension doesnt work

### ISSUE THREAD

**Issue by MikeSundaysProgrammer** [Scony/godot-gdscript-toolkit#111]
I installed the vs code gdscript formatter  extension, python, pip and the GDToolkit module. Then i reloaded the engine and when i clicked save it didnt format(i have format on save enabled and ut works with other formatters). It also didnt execute the commands organize code and multiline into singleline comments.
Btw i saw in the bottom panek that vs code is recognizing the files as gdscript.
Thanks in advance for any help,

**Comment by MikeSundaysProgrammer** [comment]
Could someone answer?

**Comment by Scony** [comment]
hi, have you followed https://github.com/Scony/godot-gdscript-toolkit/tree/master/editor-plugins/vscode ?

**Comment by MikeSundaysProgrammer** [comment]
@Scony first thanks for the reply. Second i have followed the guide and the gdtoolkit seems tl be working because i can run gdformat from the cmd

**Comment by Scony** [comment]
@Razoric480

**Comment by MikeSundaysProgrammer** [comment]
> @Razoric480

What do you mean?

**Comment by Razoric480** [comment]
He is tagging me as I made the VSCode port .

**Comment by MikeSundaysProgrammer** [comment]
Ah ok

> He is tagging me as I made the VSCode port. I'll try to investigate when I have the time.

Ah ok

**Comment by MikeSundaysProgrammer** [comment]
I changed computer and now the extension kind of works except that I am facing the issue #125
