### ISSUE TITLE
Linter: report columns as well as lines

### ISSUE THREAD

**Issue by vincens2005** [Scony/godot-gdscript-toolkit#120]
Most linters report a column where the error is as well as a line. This would be useful to have in gdlint

**Comment by Scony** [comment]
I've been thinking about it recently as with the advent of multi-statement lambda support new lexer has been introduced. Now, the information about columns is even worse. Therefore I think, for now there's not much sense of adding it as it will quite often report 0 anyway.
I'll revisit this in the future tho.
