### ISSUE TITLE
pop os - infinite format runner

### ISSUE THREAD

**Issue by Levrault** [Scony/godot-gdscript-toolkit#125]
Hi, 

I'm running pop os 21.04 beta and vscode 1.57.1

gdtoolkit is installed with gdlint

But every time I run the formatter in vs code, I got the running notification but nothing happens. The gdformat command run fine when I use it in the terminal.

![Screenshot from 2021-06-29 09-42-30](https://user-images.githubusercontent.com/1162446/123808081-6f711580-d8be-11eb-857e-87673a5432bc.png)

Thanks

**Comment by MikeSundaysProgrammer** [comment]
The same thing is happening with me on windows 10.
![image](https://user-images.githubusercontent.com/59772138/123826782-fbebfa00-d8f7-11eb-9d9a-b4e9df2e3f4f.png)

**Comment by Scony** [comment]
@igordreher is it possible that this issue is a regression after your recent change?

**Comment by igordreher** [comment]
@Scony Sorry for late response,
I don't think it is related to the changes I made, since it seems to work fine. But it's hard to tell.

@Levrault Is it possible for you to test with older versions?

**Comment by Levrault** [comment]
I rollback on the 3 previous version and still no update. On the 1.2.1, the formatter is just not executed without any indication, only on the 1.2.2 there is something happening but it still the infinite runner

**Comment by Levrault** [comment]
I found a workaround that could help other in my situation.

I installed the vscode extension [run on save](https://marketplace.visualstudio.com/items?itemName=emeraldwalk.RunOnSave) and add this the my settings.json

```
"emeraldwalk.runonsave": {
    "commands": [
        {
            "match": "\\.gd$",
            "isAsync": true,
            "cmd": "gdformat ${file}"
        }
    ]
}
```

Now it's working, good enough for me since the original issue itself can be hard to fix
