### ISSUE TITLE
gdlint: Check for docstrings

### ISSUE THREAD

**Issue by rgson** [Scony/godot-gdscript-toolkit#133]
Could gdlint warn about missing docstrings at the top of scripts?

I'm thinking of something similar to pylint's "Missing module docstring (missing-docstring)".

The [official style guide](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#class-declaration) recommends adding docstring comment near the top, after `tool`, `class_name` and `extends`.

**Comment by Scony** [comment]
That's too pedantic to add as a regular check, but I agree it will be a pretty cool remark-check. For that, however, we will need check importance levels just like `pylint` does. So it will be implemented for `4.x`.

**Comment by Scony** [comment]
Given that the `gdtoolkit` is in maintenance mode now, I don't think check levels (and thus "remarks") will ever be implemented.
