### ISSUE TITLE
gdformat: `static func` gets fewer surrounding blank lines than plain `func`

### ISSUE THREAD

**Issue by rgson** [Scony/godot-gdscript-toolkit#138]
`static func` definitions get fewer surrounding blank lines than plain `func` definitions. I believe this is unintentional. I'd expect them to keep the same formatting.

Example:
```sh
> head test.gd
func foo():
        pass


func bar():
        pass


func baz():
        pass
                                                                                
> gdformat test.gd
0 files reformatted, 1 file left unchanged.
                                                                                
> sed -i 's/func/static func/' test.gd
                                                                                
> gdformat test.gd                    
reformatted test.gd
1 file reformatted, 0 files left unchanged.
                                                                                
> head test.gd
static func foo():
        pass

static func bar():
        pass

static func baz():
        pass
```

**Comment by Scony** [comment]
@rgson can you share your `gdformat --version` ?

**Comment by Scony** [comment]
I bet it's an older one. In `3.3.1` this should not be the issue. There's event a test for that:
https://github.com/Scony/godot-gdscript-toolkit/blob/master/tests/formatter/input-output-pairs/static-function-surroundings.in.gd
https://github.com/Scony/godot-gdscript-toolkit/blob/master/tests/formatter/input-output-pairs/static-function-surroundings.out.gd

**Comment by rgson** [comment]
You're right. I _though_ I had verified with the newest version from `master`, but I must've failed to adjust my PATH correctly.

Sorry about the noise.
