### ISSUE TITLE
Godot editor plugin

### ISSUE THREAD

**Issue by DonatienBdR** [Scony/godot-gdscript-toolkit#141]
Hello,

First of all, thank you for this useful toolkit !

I wrote and submitted a plugin to call "gdformat" from inside the Godot editor : https://godotengine.org/asset-library/asset/1057

If you want, you can link to it in the editor-plugins folder (or I can submit a PR to do so).

Of course, if you don't want your toolkit to be used that way, I can remove the plugin from the asset library.

Have a nice day !

**Comment by Scony** [comment]
I've added it as submodule - good job btw.
In general I don't have enough time to create such a fancy plugins as you just did, so I'm glad you did it :)
