### ISSUE TITLE
Support for built-in script

### ISSUE THREAD

**Issue by univeous** [Scony/godot-gdscript-toolkit#144]
![image](https://user-images.githubusercontent.com/40604180/139876553-2b169bf9-ee2e-46d0-acc4-5b8f2e7a7c44.png)

as the screenshot said, a built-in script is embedded into a scene file(.tscn). 
It will be great if we can format these scripts too.

**Comment by Scony** [comment]
This can be done using this plugin: https://gitlab.com/DonatienBdR/gdformat-plugin
