### ISSUE TITLE
Using reserved keywords as part of expressions is not detected as an error while parsing

### ISSUE THREAD

**Issue by 98teg** [Scony/godot-gdscript-toolkit#147]
As I use `gdparse` with the following piece of code:
```gdscript
func foo():
    if a == if:
        pass
```
It prints out an AST as if there were no errors present.  Shouldn't it produce a parsing error?

**Comment by Scony** [comment]
Well, it depends on the approach. In `gdtoolkit` the approach is to have loosened grammar in the sense that it accepts slightly more than the actual `Godot` engine. This gives some extra flexibility useful especially in case of formatting.
Granted the above, the code you posted is fine.
If we'd have a compiler in `gdtoolkit` then it would be precisely its job to throw an error on the above code.

**Comment by 98teg** [comment]
I wasn't sure if it was intended. Thanks for clarifying!
