### ISSUE TITLE
Formatter does not use multiple lines for methods with a static return type

### ISSUE THREAD

**Issue by OverloadedOrama** [Scony/godot-gdscript-toolkit#148]
For method declarations that go beyond the 100 character-per-line limit, the formatter usually uses multilines to separate the arguments. However, when the method declaration line also has a return type that makes the line go beyond 100 characters, it seems that the formatter does not do anything, which creates issues with the linter that outputs `max-line-length` errors. An example of this case is [this line](https://github.com/Orama-Interactive/Pixelorama/blob/master/addons/gdgifexporter/gif-lzw/lzw.gd#L150):
`func decompress_lzw(code_stream_data: PoolByteArray, min_code_size: int, colors: PoolByteArray) -> PoolByteArray:`

The formatter does not do anything about this, but the linter [outputs an error](https://github.com/Orama-Interactive/Pixelorama/runs/4355362183). As far as I am aware, there is no way to currently have both the formatter and the linter not throw any errors without removing the method's return type.

**Comment by Scony** [comment]
Definitely a bug in formatter, thanks.
As a workaround, you can `# gdlint: ignore=max-line-length` inline or in the line before
