### ISSUE TITLE
Create a separate README.md on linter chcecks

### ISSUE THREAD

**Issue by Scony** [Scony/godot-gdscript-toolkit#15]

**Comment by NathanLovato** [comment]
If you're going to list all available tests, I'd generate docs from the code, like we did for Power Sequencer: https://www.gdquest.com/docs/documentation/power-sequencer/reference/

With a few lines of code, you can collect all docstrings and data from... whatever, and convert it to json or write it as markdown. The code below was written by my teammate razvan, it generates all the json data for the webpage above.

```py
import json
import operator as op
import os.path
import sys

sys.path.append(os.path.abspath(os.path.join("..", "..")))

import operators as ops


if __name__ == "__main__":
    os = dir(ops)
    os = filter(lambda o: o[0].isupper(), os)
    os = map(lambda o: op.attrgetter(o), os)
    os = map(lambda o: o(ops), os)
    os = map(lambda o: op.attrgetter("bl_idname", "doc")(o), os)
    os = {k: v for k, v in os if v != {}}
    os.update(ops.doc)

    json.dump(os, open("shortcuts_docs.json", "w"), indent=4, sort_keys=True)
```

**Comment by Scony** [comment]
I will try it, thanks!

**Comment by Scony** [comment]
I just did simple wiki page: https://github.com/Scony/godot-gdscript-toolkit/wiki/Linter
