### ISSUE TITLE
Document how to use comments to ignore linting rules for specific lines of code etc. (and other directives)

### ISSUE THREAD

**Issue by jamie-pate** [Scony/godot-gdscript-toolkit#150]
It looks like you can use a comment like this to ignore a specific line of code:
```gdscript
# Mode is actually an enum...
# gdlint: ignore=constant-name
const Mode := preload('somescript.gd').Mode
```
https://github.com/Scony/godot-gdscript-toolkit/blob/4f8fc4f6a022c1ab068933237cd503d01731e6ca/gdtoolkit/linter/__init__.py#L155

But the readme does not mention this.

If there are any other 'directives' you can add in code comments it would be helpful to have them documented as well.

**Comment by Scony** [comment]
done in wiki: https://github.com/Scony/godot-gdscript-toolkit/wiki/Linter
