### ISSUE TITLE
UnicodeDecodeError on windows

### ISSUE THREAD

**Issue by MatteoPiovanelli-Laser** [Scony/godot-gdscript-toolkit#158]
Just installed the toolkit with `pip3 install 'gdtoolkit==3.*'`
Launched `gdformat --diff .` in the project folder.
I get this output in my terminal:
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\Scripts\gdformat.exe\__main__.py", line 7, in <module>
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\__main__.py", line 69, in main
    _check_files_formatting(files, line_length, arguments["--diff"], safety_checks)
  File "C:\Users\admin\AppData\Roaming\Python\Python310\site-packages\gdtoolkit\formatter\__main__.py", line 90, in _check_files_formatting
    code = fh.read()
  File "C:\Program Files\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 558: character maps to <undefined>
```
Searching online lead me to https://stackoverflow.com/a/49562606

My guess would be that explicitly setting the encoding to use when opening the file in https://github.com/Scony/godot-gdscript-toolkit/blob/ca2abeeb8723e9951ac028dff4ef12563fd7ae1d/gdtoolkit/formatter/__main__.py#L89 would fix this, but I'm not sure about all the possible implications this may have. I think Godot by default saves encode files as UTF8, but I'm not sure.

**Comment by Scony** [comment]
@MatteoPiovanelli-Laser would you be able to share the file/part of the file which fails?

**Comment by MatteoPiovanelli-Laser** [comment]
Here's a link to it (from the repo I forked it from)
https://github.com/Orama-Interactive/Pixelorama/blob/master/src/Preferences/HandleLanguages.gd

**Comment by HolonProduction** [comment]
Starting from 72f9faf4820a2c905aabb33b8c45ccabf115e359 all files are loaded with utf-8 encoding. The file will load without problems on the `master` branch. So basically this commit needs to be backported or cherrypicked or watever advanced git magic exists for this.

**Comment by Scony** [comment]
Fixed by [4292c4a](https://github.com/Scony/godot-gdscript-toolkit/commit/4292c4a0392a85cd92d4becb38dba13a717d4aa2), to be released in `3.5`

**Comment by Prikalel** [comment]
and where is 3.5 release? only 3.4.0 and 4.0.0 are available 🤔

**Comment by FelixNemis** [comment]
Just checked and both #167 and #149 are indeed fixed when running through the command line. As of the change in code_formatter.py in [5f0da8f](https://github.com/Scony/godot-gdscript-toolkit/commit/4292c4a0392a85cd92d4becb38dba13a717d4aa2) it also works in VSCode (would be nice to have a version bump for this)
