### ISSUE TITLE
Fix order with gdformat

### ISSUE THREAD

**Issue by sh-cho** [Scony/godot-gdscript-toolkit#164]
Hi, I assume `class-definitions-order` rule is not fixed by gdformat for now.

Is there a plan to support fix-ordering with gdformat? (or I just maybe misconfigured something?)

**Comment by Scony** [comment]
Hey. There was such a discussion but it was concluded that it must be done as a separate tool: https://github.com/Scony/godot-gdscript-toolkit/issues/60
The rationale is that formatter should not (in any language) change the parse tree structure too much.

Anyway, such a tool is not planned in the near future. It's quite complex to do btw. as I'd have to implement a basic compiler to be able to reason about some complex scenarios like dependencies between definitions.
