### ISSUE TITLE
Gdformat removes Polish characters

### ISSUE THREAD

**Issue by Davilarek** [Scony/godot-gdscript-toolkit#167]
Before:
![image](https://user-images.githubusercontent.com/62715937/174488196-b9ca8b3c-df68-4c44-b7d3-b6c7632eb86e.png)
After:
![image](https://user-images.githubusercontent.com/62715937/174488230-1e85b9e4-cfd1-4ffe-88d8-4dcdf9ac3899.png)

using Visual Studio Code extension https://marketplace.visualstudio.com/items?itemName=Razoric.gdscript-toolkit-formatter

**Comment by aappaapp** [comment]
@Scony Is this fixed in 4292c4a? Could you update the VSCode extension if it is?

**Comment by Scony** [comment]
> @Scony Is this fixed in [4292c4a](https://github.com/Scony/godot-gdscript-toolkit/commit/4292c4a0392a85cd92d4becb38dba13a717d4aa2)? Could you update the VSCode extension if it is?

yes, I'll do

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.

**Comment by Davilarek** [comment]
As far as I know the extension uses this toolkit under the hood.
Haven't tested yet but using the toolkit without extension will produce the same results.
By that I mean all issues that have "extension" or "vscode" in description not necessarily mean that it is the extension producing the issue.

**Comment by Scony** [comment]
@Davilarek I've tested all of them and none reproduces w/o extension. Same goes for this one.
