### ISSUE TITLE
gdformat creates a line longer than 100 symbols and gdlint complains about it

### ISSUE THREAD

**Issue by AndreyNautilus** [Scony/godot-gdscript-toolkit#168]
In my project I run both `gdlint` and `gdformat` and I found something what seems like a bug.

I have a file with the following content:
```
static func on_quest_finished(_state: GameState, _quest_type: String, _iker_id: int, _etadata: Dictionary):
	pass
```
The line with function declaration is 107 characters long, so `gdlint` complains about it, but `gdformat` is perfectly fine with this code:
```
$ gdlint tmp/test.gd
tmp/test.gd:1: Error: Max allowed line length (100) exceeded (max-line-length)
Failure: 1 problem found
$ gdformat tmp/test.gd  --diff
1 file would be left unchanged
```

If I manually change the code so it fits in 100 symbols:
```
static func on_quest_finished(
	_state: GameState, _quest_type: String, _iker_id: int, _etadata: Dictionary
):
	pass
```
`gdlint` is happy, but `gdformat` wants to revert it to oneline (and violate the 100 length rule):
```
$ gdlint tmp/test.gd
Success: no problems found
$ gdformat tmp/test.gd  --diff
would reformat tmp/test.gd
--- tmp/test.gd
+++ tmp/test.gd
@@ -1,4 +1,2 @@
-static func on_quest_finished(
-	_state: GameState, _quest_type: String, _iker_id: int, _etadata: Dictionary
-):
+static func on_quest_finished(_state: GameState, _quest_type: String, _iker_id: int, _etadata: Dictionary):
 	pass
1 file would be reformatted, 0 files would be left unchanged.
```

If I make the line in the original file 1 symbol longer (note `_metadata` vs `_etadata`):
```
static func on_quest_finished(_state: GameState, _quest_type: String, _iker_id: int, _metadata: Dictionary):
	pass
```
both `gdlint` and `gdformat` start to complain about it (as expeected):
```
$ gdlint tmp/test.gd
tmp/test.gd:1: Error: Max allowed line length (100) exceeded (max-line-length)
Failure: 1 problem found
$ gdformat tmp/test.gd  --diff
would reformat tmp/test.gd
--- tmp/test.gd
+++ tmp/test.gd
@@ -1,2 +1,4 @@
-static func on_quest_finished(_state: GameState, _quest_type: String, _iker_id: int, _metadata: Dictionary):
+static func on_quest_finished(
+	_state: GameState, _quest_type: String, _iker_id: int, _metadata: Dictionary
+):
 	pass
1 file would be reformatted, 0 files would be left unchanged.
```

The workaround is to silence `gdlint` with `# gdlint:ignore = max-line-length`, so it's not super-critical, but still it's a bug.

**Comment by Scony** [comment]
looks like some corner case that needs to be addressed - thanks for reporting it

**Comment by AndreyNautilus** [comment]
I can try to have a look at my free time if you don't mind.

**Comment by Scony** [comment]
@AndreyNautilus no need, I already know what's the problem - have to find a proper way to resolve it

**Comment by Scony** [comment]
@ngburke the thing is - patterns are not fully implemented i.e. formatter always formats them into one line. This yields lines invalid from `gdlint` PoV.

**Comment by Scony** [comment]
@AndreyNautilus multiline patterns are now supported, although the list pattern i.e.
```
match x:
  "one", "two", "three", "four", "five", .... (and so on)
```
cannot be broken into multiple lines in an elegant way due to Godot's limitations.

Please note that the above can be rewritten as:
```
if x in ["one", "two", three"]:
```
and the formatter will be able to break such array expression into multiple lines.

Regarding original issue with `static` keyword, it should be working on `master` by now.

Please retest and reopen this issue if required.
