### ISSUE TITLE
formatter: nested functions over-expanded

### ISSUE THREAD

**Issue by bend-n** [Scony/godot-gdscript-toolkit#171]
formatter formats
```gdscript
thing.call_function(Class.new({"stuffed": ["stuffy", "things"], "clutter": 0, "another_thing": "another_thing", "more_stuff_yet": "so it goes over the line limit"}))
```
to 
```gdscript
thing.call_function(
	Class.new(
		{
			"stuffed": ["stuffy", "things"],
			"clutter": 0,
			"another_thing": "another_thing",
			"more_stuff_yet": "so it goes over the line limit"
		}
	)
)
```
instead of 
```gdscript
thing.call_function(Class.new({
	"stuffed": ["stuffy", "things"],
	"clutter": 0,
	"another_thing": "another_thing",
	"more_stuff_yet": "so it goes over the line limit"
}))
```

**Comment by Scony** [comment]
that's actually done like that on purpose - this way the code is more open to modifications and it generates much smaller diffs (e.g. when using VCS like git) at the expense of more nesting levels

**Comment by bend-n** [comment]
@Scony Where in the code is the part that does the over-expansion defined?

**Comment by Scony** [comment]
> @Scony Where in the code is the part that does the over-expansion defined?

unfortunately, it's much more complex than just changing expansion strategy. To put it simply - the formatter operates in 2 modes currently:
1. Format the entire expression into one line
2. Format the entire expression to multiple lines (force over-expansion)

What you'd like is some combination of both which would be an architectural change requiring modifications in multiple places and some mechanism to deal with ambiguity.
