### ISSUE TITLE
4.0: Add unique node path support (%NodeName)

### ISSUE THREAD

**Issue by adalinesimonian** [Scony/godot-gdscript-toolkit#173]
Currently, `$%NodeName` results in:

```
Unexpected token Token('PERCENT', '%') at line 6, column 3.
Expected one of:
        * NAME
        * LONG_STRING
        * REGULAR_STRING
Previous tokens: [Token('DOLLAR', '$')]
```

**Comment by Scony** [comment]
@adalinesimonian this is valid syntax in `3.5` as well right?

**Comment by adalinesimonian** [comment]
You know, I'm not sure off the top of my head. I know that there was some mention of backporting but I don't know if it made it in or not.
