### ISSUE TITLE
vscode extension uses deprecated `python.pythonPath`

### ISSUE THREAD

**Issue by micimize** [Scony/godot-gdscript-toolkit#177]
### Edit this is all wrong – see https://github.com/Scony/godot-gdscript-toolkit/issues/177#issuecomment-1287147351

Sometimes, especially on long method definitions, the vscode extension will wrap lines that `gdformat` unwraps. Example:
```gdscript
# line length of 109
func init(_rng_key: String, movement_steps: int, _speed, _turn_rotation_speed: float = 1) -> CyclingBehavior:
    pass
```
My guess is that it is because the extension does not pass in parsed trees the way the cli does:
https://github.com/Scony/godot-gdscript-toolkit/blob/d6de6e0b28bd8d10f701e4a57c510bc56eafdc32/editor-plugins/vscode/scripts/code_formatter.py#L4
vs
https://github.com/Scony/godot-gdscript-toolkit/blob/d6de6e0b28bd8d10f701e4a57c510bc56eafdc32/gdtoolkit/formatter/__main__.py#L183-L190

Is this done for speed, and if so, could we add a flag in the extension for enabling it? Or is there some execution-context issue

**Comment by Scony** [comment]
Either vscode extension uses a different version of gdtoolkit, or the `max_line_length` is different. I can't imagine different possibilities.
Maybe you've altered the default `100` setting in the plugin?

**Comment by micimize** [comment]
Ahh nevermind – the actual issue was that i have `gdtoolkit==3.3.1` in my virtual env, but `gdtoolkit==3.40` globally, and the extension uses the latter.

Ahhh, `python.pythonPath` was deprecated in favor of `python.defaultInterpreterPath`:
https://github.com/Scony/godot-gdscript-toolkit/blob/e5ba9ea2d464e30fd60d7d6d1aaf1ab528ae4f4f/editor-plugins/vscode/src/extension.ts#L85-L87

**Comment by Scony** [comment]
ok, thanks for confirmation
