### ISSUE TITLE
[request] support %xxxx unique name.

### ISSUE THREAD

**Issue by harrisyu** [Scony/godot-gdscript-toolkit#178]
Now when your drag node with unique name to gdscript.
It will using '%xxxx', but gdformat and linter will fail.
Using '$%xxxx' is ok, but add support for '%xxxx' would be nice.

**Comment by Scony** [comment]
to be cherry-picked from master, see #173

**Comment by Scony** [comment]
@harrisyu btw. could you please provide a complete example of failing gdscript code with %-prefixed path?

**Comment by harrisyu** [comment]
> @harrisyu btw. could you please provide a complete example of failing gdscript code with %-prefixed path?

test.gd :

```gdscript

extends Node

@onready var node: Node = %Node

```

Here is the error message:

```
gdformat.exe test.gd
test.gd:

@onready var node: Node = %Node
                          ^

Unexpected token Token('PERCENT', '%') at line 3, column 27.
Expected one of:
        * LPAR
        * NUMBER
        * BIN
        * FUNC
        * LONG_STRING
        * DOLLAR
        * BANG
        * NOT
        * MINUS
        * PLUS
        * REGULAR_STRING
        * AWAIT
        * LSQB
        * CIRCUMFLEX
        * AMPERSAND
        * HEX
        * TILDE
        * LBRACE
        * NAME
Previous tokens: [Token('EQUAL', '=')]
0 files reformatted, 1 file left unchanged.
```

[test.zip](https://github.com/Scony/godot-gdscript-toolkit/files/9911876/test.zip)

**Comment by Scony** [comment]
turns out the `master` implementation was a bit broken - some stuff was missing
