### ISSUE TITLE
Formatting slow? Performance optimization?

### ISSUE THREAD

**Issue by DasGandlaf** [Scony/godot-gdscript-toolkit#180]
Hi,
I really like this, how the formatting works and everything, it's really great :)
But in my scenario, I need to use it very often, so the performance is making some trouble for me.
So I'm wondering, is there maybe some sort of way to increase the speed? Maybe leaving a persistent instance of the formatter open to reduce the startup time, or any other optimizations I can do? Maybe I could call it's functions directly or something?
Thanks!

**Comment by Scony** [comment]
Dunno the use case exactly, but if you're formatting multiple files at once, you can bundle them in one `gdformat` call like `gdformat fileA.gd fileB.gd fileC.gd`. If you're using `gdformat` on one file e.g. via some extension, make sure they underlaying `gdformat` call uses `-f` flag to skip safety checks. Other than that, there's not much you can do out of the box. If you're able to write some python code, you can quite easily write some sort of gdformat server which gets code via TCP port and responds with formatted code. It would require some client app to get the code and send to server every time you need to format the code.

**Comment by DasGandlaf** [comment]
Ah okay, thanks. I tried using the -f flag, but I see little to no difference :/
I could make a server, but I'm not that familiar with python, so I probably won't do it. But thanks for the info, I really appreciate it :)
