### ISSUE TITLE
GDScript Formatter vscode extension source code?

### ISSUE THREAD

**Issue by acelinkit** [Scony/godot-gdscript-toolkit#182]
**GDScript Formatter vscode extension**
[VSCode Marketplace](https://marketplace.visualstudio.com/items?itemName=Razoric.gdscript-toolkit-formatter) Shows this as the source for the extension.   The latest version published was 1.2.2 on June 2021.  The newest code in [this repository](https://github.com/Scony/godot-gdscript-toolkit/blob/master/editor-plugins/vscode/package.json#L5) is from May 2020 for version 1.1.2.

#179 aims to targets the extension.  It is unclear where the extension is being published from.  I was unable to get the extension to work properly and was looking for additional information.

**Comment by acelinkit** [comment]
Publisher shows as Razoric.  I see a contributor, @Razoric480.  Maybe they can provide more info.

**Comment by acelinkit** [comment]
Any updates on this?  Unclear if that VS Code extension is abandoned.

**Comment by Razoric480** [comment]
Hi. Sorry - time and energy haven't quite lined up.

The extension has been manually published by myself from the source code, with some version-bumping. I didn't include any special or fancy automation.

**Comment by acelinkit** [comment]
No problem!  Multi-artifact projects are hard to maintain.  I can look into helping out with some release automation later.  

Anyways, I tried using the extension and am getting errors attempting to format document.  Not entirely sure what is wrong.  If I run gdformat from the command line it works.  

Log Extension Host output from vscode after running format document
```
2022-12-02 21:03:42.287 [error] Error: spawn py ENOENT
	at ChildProcess._handle.onexit (node:internal/child_process:283:19)
	at onErrorNT (node:internal/child_process:478:16)
	at process.processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by Razoric480** [comment]
Strange. I can't replicate the issue on either windows or WSL (ubuntu). I'm not familiar with that error.

**Comment by Razoric480** [comment]
From the cryptic error message, it looks like some sort of failure to invoke python to run gdformat.

**Comment by acelinkit** [comment]
Windows 11
vscode 1.73.1 user installation
vscode extension GDScript Formatter 1.2.2
Python 3.11.5
gdtoolkit 3.4.0


My guess is that this has to deal with vscode installed in user context.  Something on the extension side might need to change?  I tested using `KuhnChrisEU.vscode-formatter-godot` extension and the calls to gdformat and gdlint worked.  I'll take a crack looking through the vscode extension source.

**Comment by acelinkit** [comment]
This issue was related to how python was being installed via pyenv-win.  pyenv-win creates shims that are batch files.  

https://github.com/microsoft/vscode-python/issues/15739 similar issue with pyenv-win in the vscode-python extension
https://github.com/pyenv-win/pyenv-win/issues/352 feature request to mitigate this problem in pyenv-win

Closing this issue.  Learning more that Windows is not always developer friendly.

**Comment by acelinkit** [comment]
Adding some clarity after learning a little about vscode extension debugging.  The python-shell package does not support pyenv-win environments for looking up path.  Even after setting the path manually, there appeared to be a shim issue.  I opened a feature request: https://github.com/extrabacon/python-shell/issues/277

[vscode-python extension does support paths](https://github.com/microsoft/vscode-python/blob/3698950c97982f31bb9dbfc19c4cd8308acda284/src/client/pythonEnvironments/discovery/locators/services/pyenvLocator.ts#L19-L34).  Not sure how they handle working with the pyenv shims.


The reason why `KuhnChrisEU.vscode-formatter-godot` extension works is because they just spawn a child process directly without calling python.
