### ISSUE TITLE
VSCode extension should use gdformat executable directly

### ISSUE THREAD

**Issue by facciocose** [Scony/godot-gdscript-toolkit#184]
I use `pipx` to install system utilities in isolated environments so the vscode plugin doesn't work since it cannot source the import from its vscode python environment.

It would be better to use the executable directly.

As of now I solved using another vscode extension (Run on Save) with the following setting:

```
    "emeraldwalk.runonsave": {
        "commands": [
            {
                "match": "\\.gd$",
                "isAsync": true,
                "cmd": "gdformat ${file}"
            }
        ]
    }
```

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.
