### ISSUE TITLE
Classes should be surrounded by two blank lines

### ISSUE THREAD

**Issue by mattkanwisher** [Scony/godot-gdscript-toolkit#185]
Blank lines[¶](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#blank-lines)
Surround functions and class definitions with two blank lines:

See example here https://github.com/ProjectLam/learn_music_game/pull/17/files/591527da4c873fccdf3fb0347f382fa90d178fd5#diff-267a140fca6d04dc4333bce79764a896e8da32ceba605a1e2b9d48b7c2a2ee0fR2

It deletes one of the two blank lines

**Comment by Scony** [comment]
It's expected that statements (like e.g. `extends (...)`) are separated by at most one blank line.
