### ISSUE TITLE
class-definition-order issues with enums/setters/getters

### ISSUE THREAD

**Issue by Cretezy** [Scony/godot-gdscript-toolkit#188]
I am experiencing 2 issues with enums and setters/getters in Godot 4 not respecting https://github.com/Scony/godot-gdscript-toolkit/wiki/3.-Linter#class-checks

![image](https://user-images.githubusercontent.com/2672503/207446296-03edf14d-ed98-407a-95b7-d77c6d36799a.png)
![image](https://user-images.githubusercontent.com/2672503/207446320-5cd72570-45c4-4342-a7ed-b041aaebd5f9.png)

(Here, commenting out the enum fixes the issue)

![image](https://user-images.githubusercontent.com/2672503/207446385-9c562ae5-5c21-4e0e-aa0e-0175bd35fec4.png)
![image](https://user-images.githubusercontent.com/2672503/207446392-78fd5fb8-5451-4750-a92a-16d90ea1fc75.png)

(Here, commenting out the setter fixes the issue)

**Comment by Scony** [comment]
yeah... I've enabled that check but haven't implemented that fully so far. Thanks for reporting, I'll hotfix or disable it for now.

**Comment by Scony** [comment]
should be fixed by https://github.com/Scony/godot-gdscript-toolkit/commit/78496d74a0e440a5cec25ab5e30d8d191baa0f05
