### ISSUE TITLE
pip install instructions fail on Windows

### ISSUE THREAD

**Issue by idbrii** [Scony/godot-gdscript-toolkit#194]
Instructions say:

   pip3 install 'gdtoolkit==3.*'

But that gives error:

> ERROR: Invalid requirement: "'gdtoolkit==3.*'"

You need to use double quotes:

   pip3 install "gdtoolkit==3.*"

Do double quotes work on other platforms? If so, maybe change the instructions to use them?

**Comment by Scony** [comment]
yes, they should, thanks!
