### ISSUE TITLE
Align parsing of constants to variables.

### ISSUE THREAD

**Issue by HolonProduction** [Scony/godot-gdscript-toolkit#197]
When parsing a constant statement one basically gets a list of tokens making up the statement (including `"const"` and `"="`. To determine things like type or type interference one needs to parse this list by one self.
It would be great if the way constants are parsed was aligned to the way variables are parsed. So the `"const"` keyword should not be included. The `const_stmt` would have one child of one of the following types:
- `const_assigned`
```swift
const a = "b"
```
- `const_typed_assigned` (There seems to be a typo with `class_var_typed_assgned`. Or is there a reason for this?)
```
const a: String = "b"
```
- `const_inf`
```
const a := "b"
```

Implementing this in the grammer seems to be no problem but it would propably require some changes in the formatter and linter.

**Comment by Scony** [comment]
Fully agree. I've checked with blame and it looks like this part of grammar was like this for almost 4 years now. It's time to give it some love and refactor
