### ISSUE TITLE
Update dependencies.

### ISSUE THREAD

**Issue by HolonProduction** [Scony/godot-gdscript-toolkit#199]
When installing gdtoolkit one gets prompted with a warning about deprecated installation methods. Starting from pip 23.1 (we are currently at 23.0) a special flag will be needed to install the package. The warning is caused by two packages in the dependencies.
- `future` which is in fact a dependency of `radon`. The future package is a python 2 polyfill and was already removed from the `radon` project. The change was not yet released but hopefully rubik/radon#238 will get a response soon. So no action is needed for the moment.
- The second warning comes from the `docopt` package. It has seen its last release on PiPy in 2014. The package is basically unmaintained and will see no further releases. According docopt/docopt#494 `docopt-ng` is the new maintained version of the package. It already uses the new setup process and can be used to as a drop-in replacement.

Also I don't see a reason for keeping lark at a fixed version. Is there any?

**Comment by Scony** [comment]
Sounds good, I'll take a look into it.

Regarding `lark` dependency, in the past, they've introduced major breaking changes between releases that broke `gdtoolkit` so I don't trust them anymore and therefore I prefer to update `lark` dependency manually.

**Comment by HolonProduction** [comment]
> Regarding `lark` dependency, in the past, they've introduced major breaking changes between releases that broke `gdtoolkit` so I don't trust them anymore and therefore I prefer to update `lark` dependency manually.

Seems fair. Having a look at their release history I would suspect that breaking changes were only introduced with the 1.0 update. After that they list no compat changes (there may be some smaller stuff). I guess I will give the upgrade a try when I find some time.
