### ISSUE TITLE
Unclear installation, can't use any command

### ISSUE THREAD

**Issue by Araraura** [Scony/godot-gdscript-toolkit#208]
I can't seem to run any command after installing the toolkit.

I ran "pip3 install "gdtoolkit==4.*"" in cmd in my project folder and it said it installed successfully, but running "gdlint" give me "'gdlint' is not recognized as an internal or external command, operable program or batch file."

Even after running "python" and then "gdlint" that gives me "Traceback (most recent call last): File "<stdin>", line 1, in <module> NameError: name 'gdlint' is not defined", so I think something went wrong in the installation.

**Comment by Scony** [comment]
I recall someone already had a similar problem and I think that person had 2+ versions of python installed. You can try the same command but using `pip` instead of `pip3`.
Btw. what's the platform you're using?

**Comment by Scony** [comment]
And what python version do you use?

**Comment by Araraura** [comment]
> And what python version do you use?

i'm on 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)] on win32
(not sure why it says win32 though)

**Comment by Scony** [comment]
@Araraura I'd suggest uninstalling gdtoolkit and then installing again with `--verbose` option supplied to `pip3`. Maybe it will hint us something.

**Comment by Araraura** [comment]
> @Araraura I'd suggest uninstalling gdtoolkit and then installing again with `--verbose` option supplied to `pip3`. Maybe it will hint us something.

I found the issue, it was because "C:\Users\USER\AppData\Roaming\Python\Python310\Scripts" wasn't configured in PATH. After doing that and resetting cmd, it now works.

**Comment by Scony** [comment]
Ok, cool - that information will be useful for others with same problems in the future - thanks!

**Comment by antonytrupe** [comment]
I think I just had this issue. Deleted the C:\Python312\Lib\site-packages\gdtoolkit folder and reran the pip install command as admin and it started working.
