### ISSUE TITLE
Can we have something like .gdformatrc

### ISSUE THREAD

**Issue by cpuccino** [Scony/godot-gdscript-toolkit#214]
Would be nice to have some project level format settings so it's easier to work with teams.

**Comment by Scony** [comment]
the setting like `max-line-length-allowed` or something else?

**Comment by Dan-Crane** [comment]
I think it would be handy to have a set of rules to include in the project such as:

- `avoid-equal-expressions` (Warns when both sides of a binary expression are the same).
- `avoid-long-parameter-list` (Warns when a function or method has too long a parameter list).
- `prefer-early-return` (warns when an if statement can be converted to an early return)

**Comment by Dan-Crane** [comment]
You can see how it is implemented in [DCM](https://github.com/dart-code-checker/dart-code-metrics)

**Comment by Scony** [comment]
We already have 2) and 3) in `gdlint` so I don't quite get what's that you're asking for...
