### ISSUE TITLE
Linter disabling max-public-methods with comment doesn't work

### ISSUE THREAD

**Issue by madmachinations** [Scony/godot-gdscript-toolkit#222]
I am trying to disable the `max-public-methods` rule for a particular file. I am using this comment:

```
# gdlint: disable=max-public-methods
```

Using this style of comment seems to disable other checks on this file just fine, but `max-public-methods` refuses to be disabled by this.

I have tried setting it above all public methods and for the file as a whole.

If I dump the default config and add `max-public-methods` to the array of disabled things, that works fine. But the comment seems to do nothing.

I believe I am specifying it correctly? I am using V3.5.0

**Comment by madmachinations** [comment]
This problem is also present for 4.1

**Comment by Scony** [comment]
This is fixed but has not been released yet even tho it's in `master` already.

**Comment by madmachinations** [comment]
Ah, thank you :)
