### ISSUE TITLE
Private constant names generate warnings

### ISSUE THREAD

**Issue by Malcolmnixon** [Scony/godot-gdscript-toolkit#223]
GDScript supports both public and private comments - with the private ones being omitted from generated GDScript documentation.
```gdscript
## Publicly visible constant shows up in generated documentation
const GRAVITY = 9.8

# Private constant is hidden
const _FLAGS_BUSY = 0x40
```

The default gdlint regular expression `[A-Z][A-Z0-9]*(_[A-Z0-9]+)*` does not permit leading underscores and so errors are reported:
`Error: Constant name "_FLAGS_BUSY" is not valid (constant-name)`

It seems like a similar single leading underscore should be permitted - `_?[A-Z][A-Z0-9]*(_[A-Z0-9]+)*` just as is permitted for numerous other names (functions, class-variables, etc.)

**Comment by Scony** [comment]
I think I did it on purpose to mimic pylint behavior, but I'll check once again if there's any PEP8 for that.

**Comment by Scony** [comment]
Looks like PEP8 has no strict guidelines, so let's follow Godot way - what's the Godot version you're using?

**Comment by Malcolmnixon** [comment]
We're currently targeting 4.0.3 compatibility. Thanks!

**Comment by Scony** [comment]
Ok, I'll add it to `master` then
