### ISSUE TITLE
Issue parsing unicode characters

### ISSUE THREAD

**Issue by TranquilMarmot** [Scony/godot-gdscript-toolkit#225]
If you put a unicode character somewhere in your script (i.e. `✨`) then the formatter will complain:

```
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 3133: character maps to <undefined>
```

**Comment by Scony** [comment]
@TranquilMarmot what `gdtoolkit` version do you use? I cannot reproduce the issue with latest version from `master`

**Comment by TranquilMarmot** [comment]
I'm on version `4.1.0`.

For reference, I'm running this via the [GDScript Formatter VSCode extension](https://marketplace.visualstudio.com/items?itemName=Razoric.gdscript-toolkit-formatter), so it's possible that the error is actually coming from there? The extension lists this repo as its repo, but this obviously isn't where its code lives 😝

**Comment by Scony** [comment]
> I'm on version `4.1.0`.
> 
> For more context, I'm running this via the [GDScript Formatter VSCode extension](https://marketplace.visualstudio.com/items?itemName=Razoric.gdscript-toolkit-formatter), so it's possible that the error is actually coming from there? The extension lists this repo as its repo, but this obviously isn't where its code lives 😝

actually the sources are here. I'll check if the extension is the source of the problem

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.
