### ISSUE TITLE
Breakpoint keyword generates expression-not-assigned error

### ISSUE THREAD

**Issue by Malcolmnixon** [Scony/godot-gdscript-toolkit#229]
GDScript has a [breakpoint](https://docs.godotengine.org/en/stable/tutorials/scripting/debug/overview_of_debugging_tools.html#script-editor-debug-tools-and-options) keyword useful for coding a breakpoint into a script.

This is useful for fatal error handling as follows:
```gdscript
# Detect if the operation failed
if something_went_badly_wrong:
	# Push an error into the log and console
	push_error("An fatal error occurred")

	# Break if in the debugger
	breakpoint

	# Quit the application with a non-zero exit code
	get_tree().quit(1)
```

The following is an example script which generates the error:
```gdscript
extends Node

func _ready():
	print("At start of _ready")
	breakpoint
	print("At end of _ready")
```

The error gdlint reports (with a typo on asigned) is:
```
.\new_script.gd:5: Error: expression is not asigned, and hence it can be removed (expression-not-assigned)
Failure: 1 problem found
```

**Comment by Scony** [comment]
Thanks - I wasn't aware of that.
