### ISSUE TITLE
When using the "export" keyword, a warning is displayed and not formatted.

### ISSUE THREAD

**Issue by kiku09020** [Scony/godot-gdscript-toolkit#231]
I started using this with Godot3.
When I use the export keyword in this way, I get a warning and it is not formatted.
`export var speed=200.0`

I got a warning like this
`Previous tokens: [None]`

(I am using Deepl translation. Sorry it is hard to read English...)

**Comment by Scony** [comment]
@kiku09020 what gdtoolkit version do you use? Maybe you're using 4.x version by mistake? Please note that for Godot 3 you need to use 3.x version of gdtoolkit.

**Comment by kiku09020** [comment]
Sorry, you are right, I was mistaken...
Sorry for the inconvenience.
