### ISSUE TITLE
Linter in vscode extension

### ISSUE THREAD

**Issue by nice-shot** [Scony/godot-gdscript-toolkit#232]
Hello,
It looks like the vscode extension only includes formatting and not the linting. Are there plans to add linter support?
This extension by @eddiedover seem to have it: https://github.com/eddiedover/vscode-formatter-godot
But since this one seems to be the more "official" version I think it would be better to include all the features here instead of having multiple extensions with overlapping functionality.

**Comment by EddieDover** [comment]
@nice-shot 
To be perfectly honest, my plugin simply wraps a call to gdlint (from this very gdtoolkit),
https://github.com/EddieDover/vscode-formatter-godot/blob/cc876a86f608bf69e94b3853939741fdf59eafae/src/extension.ts#L20

If anyone maintaining this codebase wants to pull in the functionality, just let me know, so I can deprecate my plugin in favor of this one.  I'd love to look into it, but my plate is a bit full for the next week or two.

**Comment by Scony** [comment]
sounds like reasonable idea - I'll try pulling that functionality in

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.
