### ISSUE TITLE
Windows UTF-8 characters still get broken on vscode extension

### ISSUE THREAD

**Issue by a690089735** [Scony/godot-gdscript-toolkit#234]
--source
![image](https://github.com/Scony/godot-gdscript-toolkit/assets/34900141/d4864489-b20d-467f-a0a6-2752080ca33c)

--formatted
![image](https://github.com/Scony/godot-gdscript-toolkit/assets/34900141/79cef274-cbab-4ee2-a137-d69bf650e768)

Formatting with the command line and path works fine, but using the VSCode plugin for formatting results in garbled text.

**Comment by shaunhegarty** [comment]
Also experiencing this with things like currency:
![image](https://github.com/Scony/godot-gdscript-toolkit/assets/11513659/d592ca65-d91c-48a7-8aeb-b2f7b6d2f2ea)
After format: 
![image](https://github.com/Scony/godot-gdscript-toolkit/assets/11513659/9b35656b-75c0-4771-83ef-da63cb9f10f3)

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.
