### ISSUE TITLE
VSCode Extension doesn't detect PyEnv Python installations.

### ISSUE THREAD

**Issue by anthonyashco** [Scony/godot-gdscript-toolkit#235]
The VSCode extension on Windows appears to look for one of the MS Store Python installations, instead of detecting the currently set Python interpreter set by PyEnv or the local virtual environment. Attempting to trigger the GDScript formatter shows the following error:
![image](https://github.com/Scony/godot-gdscript-toolkit/assets/80195780/a256eaed-e751-48e6-8f08-ff2711a206d5)
If I install the MS Store version of 3.11.6, I get the expected message that GDToolkit needs to be installed, but attempting to do so fails to trigger anything (my guess here is because calling pip in the project directory calls the PyEnv pip instead of the MS Store one).

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.
