### ISSUE TITLE
Add support for Godot 4.2 static typing for for loop variable

### ISSUE THREAD

**Issue by chrisl8** [Scony/godot-gdscript-toolkit#236]
Godot 4.2 now supports typing the variable declaration in a for loop:
https://github.com/godotengine/godot/pull/80247

However gdformat fails when this syntax is used.

As of Godot 4.2 Beta, this syntax is valid:
```
var dict := {1: 2}
for key: String in dict:
    print(key)
```

However, running gdformat on it results in this error:
`Previous tokens: [Token('NAME', 'key')]`

**Comment by neilgoodman** [comment]
I ran into this issue the other day when using Godot 4.2 beta 2. I just submitted a PR to address it. My changes are working for me locally.

**Comment by chrisl8** [comment]
Works great @neilgoodman ! Thanks so much for the quick fix! 🙏
