### ISSUE TITLE
New Lint rule: prefer-typed-signals

### ISSUE THREAD

**Issue by Shinigami92** [Scony/godot-gdscript-toolkit#245]
Name of rule is open for discussion, but what I would like to have is to trigger a lint error when there is code like:

```gd
timer.connect("timeout", self, "_on_Timer_timeout")
emit_signal("health_depleted")
emit_signal("health_changed", old_health, health)
```

instead we should use:

```gd
timer.timeout.connect(_on_Timer_timeout)
health_depleted.emit()
health_changed.emit(old_health, health)
```

**Comment by Scony** [comment]
@Shinigami92 is such old syntax even supported?

**Comment by Scony** [comment]
I think at this point Godot either has deprecation warnings for this or does not support it anymore. Therefore I don't think we really need support for this.
