### ISSUE TITLE
Bug: Class name and extends cannot be on the same line

### ISSUE THREAD

**Issue by Piesrgr8** [Scony/godot-gdscript-toolkit#248]
If you have on one line, `class_name <something> extends <node>`, the whole gdlint command will break and will result in an error on every execution. However, it still finds rule breaking code at the top.

Having two lines dedicated to class_name and extends will fix the issue.

https://hastebin.com/share/ibivanizar.lua

Discovered by: @Piesrgr8 @squarepear

**Comment by Scony** [comment]
@Piesrgr8 this issue is already fixed in `master` branch (https://github.com/Scony/godot-gdscript-toolkit/commit/ad525088fc3d4633a8577d37da1def8addfb32f4) and will be released along with `4.2` release.
If you want to use this fix right away, please install gdtoolkit from `master` branch directly.
