### ISSUE TITLE
Expose `excluded_directories` to `gdformat` and document the usage in both - linter and formatter

### ISSUE THREAD

**Issue by dolanmiu** [Scony/godot-gdscript-toolkit#250]
`pylint` has this feature with `--ignore-patterns`

Does `gdlint` have something similar?

i have installed Godot `addons`, and I want to exclude this from linting

**Comment by dolanmiu** [comment]
Found it

```
excluded_directories: !!set
  .git: null
  addons: null
```

**Comment by chrisl8** [comment]
Is this documented anywhere?

Also, does this work for `gdformat` or only for `gdlint`?

**Comment by Scony** [comment]
> Is this documented anywhere?
> 
> Also, does this work for `gdformat` or only for `gdlint`?

I've checked and it does not work for `gdformat` (although it internally uses it and sets `.git`).
Let's reopen and use this issue to bring it to `gdformat` as well as improving wiki/help pages.

**Comment by dolanmiu** [comment]
Not documented, searched through the source code to find it

**Comment by chrisl8** [comment]
This would be a nice feature add.

Currently for my GitHub actions run, I can add the `addons` folder to `gdlintrc` and then use `gdlint .`,
but for gdformat I have to use `gdformat --check $(find . -name '*.gd' -not -path "./addons/*")` to avoid including the `addons` folder.

```
    - id: run-gdformat
      run: gdformat --check $(find . -name '*.gd' -not -path "./addons/*")
    
    - id: run-gdlint
      run: gdlint .
```

Having gdformat also read the `gdlintrc` file or a similar file would allow me to use a generic GitHub action file, along with simplifying its use elsewhere in my workflow.

**Comment by chrisl8** [comment]
I believe this is now accomplished by #286

What is left is to document it. I'm not sure how to edit the Wiki though.  
Either I don't have permission or I just don't know how.

**Comment by Scony** [comment]
@chrisl8 you can't clone `https://github.com/Scony/godot-gdscript-toolkit.wiki.git` ?

**Comment by chrisl8** [comment]
> @chrisl8 you can't clone `https://github.com/Scony/godot-gdscript-toolkit.wiki.git` ?

@Scony Yes, I can clone it, but I am not aware of any way to fork it and/or to make pull requests against it.

**Comment by Scony** [comment]
Wiki entry updated, thanks!
