### ISSUE TITLE
gdformat: support raw string literals (r-strings)

### ISSUE THREAD

**Issue by Arrow-x** [Scony/godot-gdscript-toolkit#257]
Formatting this
```gdscript
func test():
	var g = r"\,? ?(i?\(.*?\))"
```
will through a massive Exception (should I post the full log?)
```
AttributeError: 'PatternStr' object has no attribute 'raw'
```
it seems that it doesn't recognize r-string that was added in [74995](https://github.com/godotengine/godot/pull/74995)

**Comment by Scony** [comment]
Correct, I've found out about Godot's support for raw strings yesterday - from release notes. It's not supported yet.
