### ISSUE TITLE
formatter: turn spaces into tabs

### ISSUE THREAD

**Issue by Scony** [Scony/godot-gdscript-toolkit#26]
since almost the whole Godot community uses tabs, this will be formatter's default

**Comment by GammaGames** [comment]
Is there a flag to use spaces? I understand tabs being default, but I prefer spaces.

**Comment by NathanLovato** [comment]
No, there are no flags. The formatter is like black, it uses the official style guide for GDScript.

You could use another program, like sed, to replace  leading tabs with four spaces:

```
gdformat **.gd
sed -iE 's/\t/    /g'
```

**Comment by GammaGames** [comment]
Ah, thank you! I use vscode and can easily run the command to convert tabs to spaces so it's not a huge deal.
