### ISSUE TITLE
Always add newline after `@rpc(...)`

### ISSUE THREAD

**Issue by tavurth** [Scony/godot-gdscript-toolkit#261]
```gdscript
@rpc("authority", "call_local", "reliable")
func some_func():
````

The above quite commonly gets refactored to:

```gdscript
@rpc("authority", "call_local", "reliable") func some_func():
```

Which seems harder to read?

In general type annotations for functions could always be on a new line?

**Comment by Scony** [comment]
Yes, I already did some changes to support it, but I think `@rpc` annotation was not taken into account. Thanks for reporting!

**Comment by Scony** [comment]
I've checked and it should actually work by now - @tavurth what version of gdtoolkit do you use?

**Comment by tavurth** [comment]
@Scony
```sh
▶ gdformat --version
gdformat 4.0.1
```

**Comment by tavurth** [comment]
Thank you! Working in `4.2.2`
