### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by ajbastien** [Scony/godot-gdscript-toolkit#264]
Windows 11 Install
python --version: Python 3.12.1
Installed GDToolkit: pip install GDToolkit
Restarted VS Code:
Python Interpreter path: C:\Users\user1\AppData\Local\Programs\Python\Python312\python.exe

Getting error when saving a GDScript file: 
ModuleNotFoundError: No module named 'pkg_resources'
Any thoughts?

**Comment by Scony** [comment]
Yeah, `pkg_resources` was deprecated for a while now, so likely it's removed now in Python 3.12... I'll align gdtookit in upcoming days. Thanks for reporting this.

**Comment by ajbastien** [comment]
That worked:
pip3 install git+https://github.com/Scony/godot-gdscript-toolkit.git

Thanks for the quick response.

**Comment by Scony** [comment]
Good, it will be a part of next gdtoolkit release. Thanks for confirming!

**Comment by MikeSchulze** [comment]
I run into same issue, it works with latest master 👍

**Comment by Bobrokus** [comment]
For me installing it via `pip` instead of `pip3` fixed it.
