### ISSUE TITLE
Option to remove space before function name when wrapping multiline

### ISSUE THREAD

**Issue by tavurth** [Scony/godot-gdscript-toolkit#266]
```gdscript
func set_shader_offset(at_position: Vector3) -> void:
	for key in ["base", "ridge", "river", "detail"]:
		%HeightmapRenderer\
			.get_material()\
			.get_shader_parameter("input_%s" % key)\
			.get_noise()\
			.set_offset(at_position * WorldHelper.CHUNK_SIZE)
```

Will become:

```gdscript
func set_shader_offset(at_position: Vector3) -> void:
	for key in ["base", "ridge", "river", "detail"]:
		(
			%HeightmapRenderer
			. get_material()
			. get_shader_parameter("input_%s" % key)
			. get_noise()
			. set_offset(
				at_position * WorldHelper.CHUNK_SIZE
			)
		)
```

I just would like to find a way to remove the `. x` space between the dot and the function name. Is this currently possible?

**Comment by Scony** [comment]
No - it's meant to be this way so that the style is uniform regardless of operator.

**Comment by tavurth** [comment]
I mean regardless of operator there will also always be a point and then a name?

**Comment by Scony** [comment]
Well, the dot is the operator just like any other like `+`, `%`, `==`, and the likes. Therefore in the above case, there will always be a whitespace after the operator.
