### ISSUE TITLE
`gdlint` do not report trailing spaces

### ISSUE THREAD

**Issue by MikeSchulze** [Scony/godot-gdscript-toolkit#272]
I want to check for invalid trailing spaces like
```gdscript
func xx() -> void: 
   pass
```

It should detect an invalid trailing space  `func xx() -> void: `

**Comment by Scony** [comment]
`gdlint` reports precisely that - what is that you have tried?

**Comment by MikeSchulze** [comment]
Hi, i just run glint on this example with latest master version.

When a row has a trailing space, it will not detect and reported.

**Comment by MikeSchulze** [comment]
I use Windows11 the GitBash. I will attach an example in the next few minutes.
