### ISSUE TITLE
Looks like the linter doesn't like negative ints being used inside an Enum{}

### ISSUE THREAD

**Issue by sleepcircle** [Scony/godot-gdscript-toolkit#28]
lark.exceptions.UnexpectedCharacters: No terminal defined for '-' at line 13 col 12

	NOWHERE = -1,
           ^

Expecting: {'NUMBER', '_NL'}
Previous tokens: Token(EQUAL, '=')

**Comment by Scony** [comment]
yep, thanks for reporting!
