### ISSUE TITLE
GDSCript Formatter not formatting, just endless progress 

### ISSUE THREAD

**Issue by stepansanda** [Scony/godot-gdscript-toolkit#280]
I installed godot-tools and GDSCript Formatter to my VS Code. When I try to format my .gd document I can only see progress at the top below the tabs part and it is not formatting. The progress is visible until I click in the document again. 
I installed both extensions through VS Code extension manager / marketplace. godot-tools seems to work pretty well, but the formatter is not formating and I cannot see any error or some kind of hint what is wrong.

**Comment by stepansanda** [comment]
I managed to make it work when I completely uninstalled VS Code from my mac and install it with godot-tools and GDScript Formatter again. I also had to remove all VS Code saved cache from my mac. So the problem was obviously on my side. 
Anyway, some sort of error dialog telling what is wrong would be nice to have so other devs having the same problem will know how to fix it.

**Comment by Scony** [comment]
VSCode extension is no longer part of this repo.
