### ISSUE TITLE
`gdlint`: Calling static private method from inside the same class raises error

### ISSUE THREAD

**Issue by hungpt-a8e** [Scony/godot-gdscript-toolkit#283]
If you try to call static private method of a class from inside the same class `gdlint` will raise an error, for example:
```gdscript
class_name Foo

func _foo() -> void:
    Foo._bar() # gdlint: Error: Private method "_bar" has been called (private-method-call)

static func _bar() -> void:
    pass
```
I think private members should be allowed to be called from inside the same class and `gdlint` should not raise errors in this situation.

**Comment by Scony** [comment]
This check is now removed.
