### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by chrisl8** [Scony/godot-gdscript-toolkit#285]
For selfish and not-super-important reasons I would like to update the dependencies to the latest.

Currently that would be changing:
https://github.com/Scony/godot-gdscript-toolkit/blob/cbd7a1dcff14cd272787a4ca497c7ff328714a6c/setup.py#L34C1-L35C28
```
        "lark[regex]==1.1.5",
        "docopt-ng==0.8.1",
```
To:
```
        "lark[regex]==1.1.9",
        "docopt-ng==0.9.0",
```

I plan to perform the update myself, check for failures, fix them, and submit a PR.

I am only making this issue to "ask permission" in case you already have a reason why you would reject such a PR and/or in case you were already working on this.

If you don't want me to do this, just let me know and close this and I will stop. Thank you!

**Comment by Scony** [comment]
Sounds good.
