### ISSUE TITLE
Weird GDFormat style guidelines

### ISSUE THREAD

**Issue by tavurth** [Scony/godot-gdscript-toolkit#295]
Regarding the provided code examples, I share the opinion that the current `GDFormat` output could be improved to align better with popular formatting conventions:

```gdscript
my_array.append({
    # no-wrap
    "some": "a",
    "thing": "b",
    "is_weird": "something very long",
})
```

The `GDFormat` currently formats it as:

```gdscript
(
    my_array
    . append(
        {
            # no-wrap
            "some": "a",
            "thing": "b",
            "is_weird": "something very long",
        }
    )
)
```

The extra newline between `append(` and `{`, as well as the space between the dot and the method name, make the code a bit harder to read and deviate from common conventions.

1. Regarding the newline between `append(` and `{`:
  - [Black for Python: Dictionaries](https://black.readthedocs.io/en/stable/the_black_code_style/future_style.html)
  - [Prettier for JavaScript: Argument Expansion](https://prettier.io/docs/en/rationale.html#argument-expansion)

2. Regarding the space between the dot and the method name:
  - [Python's PEP 8: Whitespace in Expressions and Statements](https://peps.python.org/pep-0008/#whitespace-in-expressions-and-statements)
  - [Java's Code Conventions: Whitespace](https://www.oracle.com/java/technologies/javase/codeconventions-whitespace.html)
  - [Google's C++ Style Guide: Formatting](https://google.github.io/styleguide/cppguide.html#Formatting)

And finally the Godot source code itself.

**Comment by tavurth** [comment]
I should note the example formatted differently I guess:

```python
my_array.append(
    {
        # no-wrap
        "some": "a",
        "thing": "b",
        "is_weird": "something very long",
    }
)
```

```java
my_array.append({
            "some": "a",
            "thing": "b",
            "is_weird": "something very long",
        })
```

```c++
my_array.append({
  "some": "a",
  "thing": "b",
  "is_weird": "something very long",
})
```

```javascript
my_array.append({
    "some": "a",
    "thing": "b",
    "is_weird": "something very long",
})
```

**Comment by Scony** [comment]
I think it was discussed already in some issue but I couldn't find it. Anyway - I'd love to add support for such compact conventions but the thing is that it would take a lot of time to implement. Currently, the formatter operates in 2 modes (or strategies if you will) and chooses the one that fits better at a given point:

1. "format everything to single line" - which does exactly what it says
2. "format to multiple lines" - which formats to multiple lines and potentially falls back to 1) at deeper levels.

The correct approach to implement compact multiline formatting would be to add a new, 3rd strategy and use it in cases where it fits better. Such a strategy would require implementing custom formatting rules for all parse tree nodes which (assuming full test coverage) would require tons of man-hours to implement.

Therefore-  realistically speaking - this feature probably won't ever be implemented although it would be a cool thing to have I agree.

**Comment by IntangibleMatter** [comment]
I would just like to mention that this issue is displaying itself quite clearly in the following bit of code I have. It's an array of integers, which I would like to format into groups of 6 because of texture sheet reasons, but instead I get this 32-line long monstrosity.

```gdscript
var head_offsets: PackedInt32Array = [
	5,
	5,
	5,
	5,
	5,
	5,
	0,
	0,
	0,
	0,
	0,
	4,
	0,
	-1,
	4,
	0,
	-1,
	-1,
	1,
	1,
	1,
	1,
	0,
	0,
	0,
	-2,
	0,
	0,
	0,
	-2,
]
```

**Comment by Scony** [comment]
> I would just like to mention that this issue is displaying itself quite clearly in the following bit of code I have. It's an array of integers, which I would like to format into groups of 6 because of texture sheet reasons, but instead I get this 32-line long monstrosity.
> 
> ```gdscript
> var head_offsets: PackedInt32Array = [
> 	5,
> 	5,
> 	5,
> 	5,
> 	5,
> 	5,
> 	0,
> 	0,
> 	0,
> 	0,
> 	0,
> 	4,
> 	0,
> 	-1,
> 	4,
> 	0,
> 	-1,
> 	-1,
> 	1,
> 	1,
> 	1,
> 	1,
> 	0,
> 	0,
> 	0,
> 	-2,
> 	0,
> 	0,
> 	0,
> 	-2,
> ]
> ```

as for the above - it will be possible to skip formatting of such statement once https://github.com/Scony/godot-gdscript-toolkit/issues/52 is implemented.

**Comment by Scony** [comment]
As mentioned above, workaround for this issue will be introduced as part of https://github.com/Scony/godot-gdscript-toolkit/issues/52

**Comment by Scony** [comment]
> I still find this issue incredibly frustrating.
> 
> Python is my daily language, where `black` formats things as `prettier` would.
> 
> And then coming to `gdscript`, I find that suddenly I have to fight the formatter to get things in a readable state. 😢
> 
> This has many times had me considering if I need `gdformat` in my toolbox, and I haven't switched purely because there is no available alternative at the moment.
> 
> Is there a reason why this is closed as "not planned" for the roadmap?

The true reason is that I'm planning to implement it properly within Godot itself, see `Tentative plan for followup PRs` section in the initial PR: https://github.com/godotengine/godot/pull/97383

However, if the above gets rejected or if the implementation pace is slow, then I'm going to implement more strategies within gdtoolkit.
