### ISSUE TITLE
Remove external plugins from the repo

### ISSUE THREAD

**Issue by Scony** [Scony/godot-gdscript-toolkit#296]
Since the `godot-gdscript-toolkit` project itself is quite big at this point it's quite reasonable to extract plugins like VSCode extension and the likes to separate repos. This will make this repo free from discussions which are plugin-related.

**Comment by nonolai** [comment]
> it's quite reasonable to extract plugins like VSCode extension and the likes to separate repos

What repository was the VSCode extension moved to?

**Comment by Scony** [comment]
In a recent communication with me, the core maintainer of that extension (@Razoric480) mentioned that he will most likely archive the extension so I guess there's no new repo for it.

**Comment by Razoric480** [comment]
Correct - maintaining it isn't really in the cards for me either.

All it is is a python invoker that passes the gdscript forwards through VSCode's formatter API, so someone more dedicated can probably get running pretty quickly.

**Comment by Razoric480** [comment]
There's also a dedicated formatter in the extension, at least for godot 4, so it feels low priority
