### ISSUE TITLE
formatter: comments in expressions

### ISSUE THREAD

**Issue by Scony** [Scony/godot-gdscript-toolkit#30]

**Comment by qarmin** [comment]
This issue is one year old and doesn't look that it will be fixed in near future, so can be easily this error silenced by just ignoring lines with comments?

**Comment by Scony** [comment]
@qarmin not really. During formating, the code is being built from the pure model (with comments as hints) and thus this feature must be implemented either rock solid or not at all. The hacks are not really possible here.

Since the implementation is not trivial, I'm waiting with this one till `4.0`. I'll implement it along with other major changes.
