### ISSUE TITLE
Feature: Docker Support

### ISSUE THREAD

**Issue by coillteoir** [Scony/godot-gdscript-toolkit#300]
Would you be open to the idea of adding a dockerfile to this project? I have been using it with docker and there has been no issues. I am willing to contribute one also.

### Some Reasons for it

- The toolkit can be installed and ran in one command on any compatible system.
- Some users may not have python installed, or don't wish to use pip on their host machines. 
- Many CI systems have native support for containers (especially if an organization is using Kubernetes for a build farm.)

**Comment by coillteoir** [comment]
https://hub.docker.com/repository/docker/davidlynchsd/gdtoolkit/

**Comment by Scony** [comment]
Hi, I like the idea of using docker with `gdtoolkit`, but I prefer not to add dockerfile to this repo. The reasoning is simple - it's very much a standalone thing and I'd like to keep this repo as clean as possible.

**Comment by coillteoir** [comment]
Fair enough no worries
