### ISSUE TITLE
Error trying to install toolkit with pip3 on Linux

### ISSUE THREAD

**Issue by wyattbiker** [Scony/godot-gdscript-toolkit#301]
Got an error when trying to install the toolkit. I don't know the python environment enough, but I resorted to using the following command: 
`~$ pipx install "gdtoolkit==4.*" `

Maybe add comment in the documentation about it. I am using Ubuntu.

Here is error message:
```
~$ pip3 install "gdtoolkit==4.*"
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

```

**Comment by Scony** [comment]
Good idea, thanks!

**Comment by dac514** [comment]
I am also getting this error. 
Python 3.12.3
Workaround was:

```
pipx install "gdtoolkit==4.*"
pipx inject gdtoolkit setuptools
```

The second line, inject, took a while to figure out. It looks like setuptools is deprecated in python 3.12, needs to be added to requirements or something. Sources:

- https://stackoverflow.com/questions/7446187/no-module-named-pkg-resources
- https://github.com/python/cpython/issues/95299

**Comment by Scony** [comment]
The wiki has been updated. As for the `setuptools` - it looks like it's os-depented. I'll followup on that in case of problems.
