### ISSUE TITLE
Bitshift operators get formatted as boolean operators

### ISSUE THREAD

**Issue by anup-the-magic** [Scony/godot-gdscript-toolkit#304]
Minimal example:

```
var foo = 1 << 2
```

## Expected
Retain formatting

## Actual
```
var foo = 1 < < 2
```
(note, this is a syntax error)

**Comment by Scony** [comment]
Looks like bug, thanks for reporting

**Comment by Scony** [comment]
@anup-the-magic I cannot reproduce with latest gdtoolkit - what version do you use?

**Comment by anup-the-magic** [comment]
D'oh, I'm so sorry, thought I was using this to format but seems like default formatter was godot-tools, where the issue was already reported!

gonna go ahead and close this, I can't reproduce!

**Comment by Scony** [comment]
Thanks for clarifying!
