### ISSUE TITLE
A few config questions (calling private function from static function)

### ISSUE THREAD

**Issue by NamespaceV** [Scony/godot-gdscript-toolkit#307]
1. Can I turn off warnings for private method calls in static functions of the class. I don't want this to be reported as an error:
```
class_name X;

static func create() ->X:
   var x = X.new()
   x._private()
   return x

func _private():
   pass
```

2. Can I turn off errors on private/public functions order.
I often mix private and public functions to keep them in coherent regions.
I would like to keep all the other order checks, but i don't want to get errors when private and public functions are mixed.

**Comment by NamespaceV** [comment]
I created a `.gdlintrc` to tweak a few settings. I can't find a good way for both above.

2. I guess private and public functions mixing is not reported at all, so its kinda fine for me...
I would like to force subclass class definitions at the end of the file though

1. I often use static factory functions in my classes.
I think this is dglint error to report private function access as an error
In a static function of the class for this private function.

I do want to have access to privates of other classes reported.
And i'd rather not annotate all my factory functions with
```
# gdlint: disable=private-method-call
func SomeWrongName():
    pass
# gdlint: enable=private-method-call
```
nor
```
# gdlint: ignore=private-method-call
```
especially as i want private method calls to be reported. But not when static methods of the class where function is defined are called.

**Comment by Scony** [comment]
Actually, the `private-method-call` check was removed in fcd3067585733b897b6a8b02da75fd53341b4285 so closing this issue as not relevant anymore
