### ISSUE TITLE
gdradon: Can't use cc with files with getters and setters

### ISSUE THREAD

**Issue by pmiller3** [Scony/godot-gdscript-toolkit#311]
I'm trying to use a file, for example `gdradon_error.gd`  with the command `gdradon cc gdradon_error.gd`, but I get an error:
```
Cannot process file 'gdradon_error.gd' due to exception: Token('RULE', 'property_body_def')
```

This happens to me with any file with a getter or setter on a property, such as:
```
extends Node

var can: int
var cant: int:
	get:
		return cant
var wont: int:
	set(value):
		wont = value


func _ready():
	can = 1
	cant = 0
	wont = 0
```

**Comment by Scony** [comment]
@pmiller3 what version of gdtoolkit do you use?

**Comment by Scony** [comment]
I've double-checked and I'm certain this issue was reported for old version of GDToolkit. Therefore closing as this is fixed now.

**Comment by pmiller3** [comment]
Apologies for the delay - it appears `4.2.2`.  I'll try to reproduce, update, and try again.

**Comment by pmiller3** [comment]
@Scony Easy enough, that indeed passes.  Thank you!
