### ISSUE TITLE
Experiment in Godot Demo Project

### ISSUE THREAD

**Issue by m21-cerutti** [Scony/godot-gdscript-toolkit#313]
Hello,

It's not quite an issue but it seems defaults rules are not completely folllowing the [gdscript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html), I have tried to use it inside
https://github.com/godotengine/godot-demo-projects/pull/1085 but it wasn't working out-of-the-box (but it would be great https://github.com/godotengine/godot-demo-projects/issues/1090 to have it).

I think it could be great that we can use it inside godot demo project, at least until
https://github.com/godotengine/godot-proposals/issues/3630

**Comment by Scony** [comment]
Well, we can try to improve following the [gdscript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) - can you point me mismatch points?

**Comment by Scony** [comment]
Let's do the following - please open new issues for the mismatches vs [gdscript style guide](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html) and I'll try to address those if possible
