### ISSUE TITLE
Support for .tscn files

### ISSUE THREAD

**Issue by nubels** [Scony/godot-gdscript-toolkit#315]
I really like this toolkit. I hope this is the right place for feature requests.

Are there any plans to extend the linter to work with .tscn files? Here are some features I would like to see.

- ensure that the names of nodes are PascalCase
- ensure that no signals are connected via the node tab
- ensure that there are no built-in scripts

**Comment by Scony** [comment]
Well, there was a plan in the past - I even started creating a Godot Project Linter (`gdplint` - https://github.com/Scony/godot-gdscript-toolkit/commit/8df572340a6bc4a7ced7437520f70a1dd0236072) that was supposed to be a project-aware linter able to lint cross-gd-script interactions as well as `.tscn` files, but realistically speaking, this is not doable for me as recently I have time only for maintenance (which btw. takes a lot of time itself).
