### ISSUE TITLE
gdlint : Add support for virtual function

### ISSUE THREAD

**Issue by copsfuraxx** [Scony/godot-gdscript-toolkit#320]
In Godot, functions that start with an underscore (_) are typically considered private. However, these functions can also be virtual methods, which might require special handling. A virtual method in Godot is usually indicated by the presence of the pass keyword in the function body.

**Comment by Scony** [comment]
> In Godot, functions that start with an underscore (_) are typically considered private. However, these functions can also be virtual methods, which might require special handling. A virtual method in Godot is usually indicated by the presence of the pass keyword in the function body.

So what is your idea the linter should do with virtual methods?

**Comment by copsfuraxx** [comment]
> So what is your idea the linter should do with virtual methods?

I use a virtual function in a state machine, and the linter throw an error because of a call to that method from outside the class. So I think it can be nice to detect virtual function to not throw that error.

**Comment by Scony** [comment]
> > So what is your idea the linter should do with virtual methods?
> 
> I use a virtual function in a state machine, and the linter throw an error because of a call to that method from outside the class. So I think it can be nice to detect virtual function to not throw that error.

Ahh, ok. This check will be removed as part of https://github.com/Scony/godot-gdscript-toolkit/issues/308 so closing this issue as duplicate.
