### ISSUE TITLE
GDLint: Add support for type formatting checks

### ISSUE THREAD

**Issue by MikeSchulze** [Scony/godot-gdscript-toolkit#323]
According to the official style guide for typed variables https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#declared-types
the linter should validate the syntax of typed variables.

good:
`var foo: int`
`var foo: int = 1`
`var foo := 1 as int`
`var foo := 1.0`
`var bar := my_func()`
`var bar: int = my_func()`
`func my_func(arg1: int) -> int:`
`func my_func(arg1: int = 1) -> int:`
`func my_func(arg1 := 1.0) -> int:`

bad:
`var foo :int`
`var foo:= 1`
`var foo:=1`
`var bar = my_func()`
`var bar:= my_func()`
`var bar:int = my_func()`
`func my_func(arg1:int) -> int:`
`func my_func(arg1 :int = 1) -> int:`
`func my_func(arg1:=1) -> int:`

### enable variable typed syntax check
`typed_variable_syntax: true`

### enable parameter typed syntax check
`typed_argument_syntax: true`

### enable strict typed check
`typed_strict: true`

**Comment by Scony** [comment]
You're referring to formatting and that's what `gdformat` does already. You can pass `--check` to it and it will tell if formatting is correct or not. Such checks could also be added to linter, but in general it's not worth it to maintain the same feature twice (in two separate tools).

**Comment by MikeSchulze** [comment]
Sorry, but a linter and a formatter are different things.
I want to use the linter in a shared project and not force users to use the formatter.
I understand your point about not using the same function twice. Maybe you should think about reusing/sharing the formatting code in the linter to minimize your effort.
I think it's a shame to block new functions with this argument, it ultimately makes the linter redundant according to this statement.
I

**Comment by Scony** [comment]
> Sorry, but a linter and a formatter are different things. I want to use the linter in a shared project and not force users to use the formatter. I understand your point about not using the same function twice. Maybe you should think about reusing/sharing the formatting code in the linter to minimize your effort. I think it's a shame to block new functions with this argument, it ultimately makes the linter redundant according to this statement.

I see your point and I agree that in an ideal world, features could be spread across formatter and linter.
However, I basically don't have the resources to maintain such a solution.

As for the code sharing - it's not that straightforward as formatter rebuilds code from scratch (from parse tree) while in case of linter you'd like to have ad-hoc checks.
