### ISSUE TITLE
How do you fix: Unexpected token Token('TYPE_HINT'

### ISSUE THREAD

**Issue by njt1982** [Scony/godot-gdscript-toolkit#324]
Hi - first - thanks for this package, its fantastic!

I've run the gdformat and it did a great job. Love it.

I'm getting a lot of errors like this when I lint, though:

```
./scripts/botanica.gd:

				if funds.funds >= plant.unlock_price:
                                   ^

Unexpected token Token('TYPE_HINT', 'funds.funds') at line 50, column 8.
Expected one of:
	* IN
	* SEMICOLON
	* "||"
...
...
	* "%="
Previous tokens: [Token('NAME', 'if')]
```

The code in question looks like this:
```
			btn.text = "$%d" % plant.unlock_price
			btn.connect("pressed", func():
				if funds.funds >= plant.unlock_price:
					plant.locked = false
```

`funds` is defined as `@export var funds : Funds` and plant comes from a loop as `for plant : Plant in Global.plant_book.plants:`... So they're both "typed". Within each class, `funds.funds` is `@export var funds: int = 0` and `plant.unlock_price` is `@export var unlock_price: int = 1` (again, both "typed"...). Functionally, the code works as expected.

What does this 'TYPE_HINT' error mean? It feels like the linter can't work out the variable type?

If it helps, I'm also getting it here:
```
./scripts/states/plant_popup_menu_state.gd:

		state_machine.reset_to_starting_state()
                ^

Unexpected token Token('TYPE_HINT', 'state_machine.reset_to_starting_state') at line 20, column 3.
```

Which, in context, is:
```
	menu.connect("plant_selected", func(plant: Plant):
		plant_selected.emit(plant)
		state_machine.reset_to_starting_state()
	)
```

The only thing these two have in common is that they're both calls inside lambda functions? Is that relevant?

I'm running 4.3.1 on OSX with Python 3.12:
```
pipx install gdtoolkit
  installed package gdtoolkit 4.3.1, installed using Python 3.12.6
  These apps are now globally available
    - gd2py
    - gdformat
    - gdlint
    - gdparse
    - gdradon
```

LMK if you need anymore info :)

**Comment by njt1982** [comment]
Also getting it on:
`Unexpected token Token('TYPE_HINT', 'build_hut.emit') at line 18, column 3. which is, again, inside a lambda

```
	menu.connect("build", func(type):
		close_menu()
		build_hut.emit(type)
	)
```

I wonder if it's losing the types due to the scope? Am I meant to be doing something to pass the outer variable in? I know in PHP, anonymous functions have to use `fn($param) use ($thing)`...

**Comment by Scony** [comment]
Thanks. You're basically hitting a problem that multiline lambdas are not supported. See discussion in https://github.com/Scony/godot-gdscript-toolkit/issues/191
Good news is that the support is coming soon, so stay tuned!

**Comment by njt1982** [comment]
Ahh ok - so maybe the better/alternative fix would be to refactor those into proper callable functions? Maybe its a "code smell" that I have multiline lambdas...

Thanks for getting back to me so quickly!

**Comment by Scony** [comment]
First of all, I need to correct myself by saying "multi-statement lambdas are not supported. " rather than "multiline lambdas are not supported. ".

> Ahh ok - so maybe the better/alternative fix would be to refactor those into proper callable functions? Maybe its a "code smell" that I have multiline lambdas...
> 
> Thanks for getting back to me so quickly!

My personal opinion is that having multi-statement lambda is a code smell, so to me lambdas such as:
```
var foo = func(): return [
    1,
    2,
    3,
]
```
are ok, but lambdas such as:
```
var foo = func(): var x = 1 ; return x
# or
var bar = func():
    bat()
    bay()
```
are not.

btw. uni-statement lambdas are supported by `gdformat` currently so you can do stuff like:
```
var foo = func(): return (
    some == 1
    && some_other > 0
    && baz(some) < -1
)
```
etc.

However, in the community, there's a very strong need for multi-statement lambdas so I'm currently working on implementing them.

Back to your specific case - I personally would recommend you to use regular, named functions for handling signals, so I'd use e.g. `func _on_menu_plant_selected(): (...)` etc.
