### ISSUE TITLE
gdlint errors on var names beginning with _

### ISSUE THREAD

**Issue by Jack-023** [Scony/godot-gdscript-toolkit#329]
In gdscript you can prepend an _ to the name of a variable to acknowledge that it is intentionally unused, to avoid triggering `UNUSED_VARIABLE` warnings. An example where this is common is in the built-in processing callbacks. eg
```gdscript
func _process(_delta: float) -> void:
    pass
```
When doing this elsewhere in scripts, gdlint will report an error `Function-scope variable name "_ignored" is not valid (function-variable-name)`.

I can't see anywhere in the official style guide that suggests this shouldn't be allowed. If gdlint uses rules outside of the official style guide is there somewhere they can be viewed?

**Comment by Scony** [comment]
Well, this particular rule was rather motivated by pylint - it was introduced before official style guide existed in its current form.

If you think about it, in the case of functions parameters sometimes cannot be avoided. Therefore it's logical to allow prepending `_`. In other cases, instead of writing `var _foo` once can just avoid writing it in the first place.

Anyway, if you really want to alter this behavior, you can check gdtoolkit wiki: https://github.com/Scony/godot-gdscript-toolkit/wiki/3.%20Linter#tweaking-default-check-settings It allows you to create `gdlintrc` file with custom rules. By default it will be something like:
```
class-load-variable-name: (([A-Z][a-z0-9]*)+|_?[a-z][a-z0-9]*(_[a-z0-9]+)*)
class-name: ([A-Z][a-z0-9]*)+
class-variable-name: _?[a-z][a-z0-9]*(_[a-z0-9]+)*
constant-name: '[A-Z][A-Z0-9]*(_[A-Z0-9]+)*'
disable: []
enum-element-name: '[A-Z][A-Z0-9]*(_[A-Z0-9]+)*'
enum-name: ([A-Z][a-z0-9]*)+
function-argument-name: _?[a-z][a-z0-9]*(_[a-z0-9]+)*
function-arguments-number: 10
function-preload-variable-name: ([A-Z][a-z0-9]*)+
function-name: (_on_([A-Z][a-z0-9]*)+(_[a-z0-9]+)*|_?[a-z][a-z0-9]*(_[a-z0-9]+)*)
function-variable-name: '[a-z][a-z0-9]*(_[a-z0-9]+)*'
load-constant-name: (([A-Z][a-z0-9]*)+|[A-Z][A-Z0-9]*(_[A-Z0-9]+)*)
loop-variable-name: _?[a-z][a-z0-9]*(_[a-z0-9]+)*
signal-name: '[a-z][a-z0-9]*(_[a-z0-9]+)*'
sub-class-name: _?([A-Z][a-z0-9]*)+
```
and as you can see, the `function-argument-name` and e.g. `class-variable-name` allow `_` prefix while e.g. `function-variable-name` does not. You can change it in the config file and `gdlint` won't raise errors again.

**Comment by Jack-023** [comment]
I wasn't aware of the wiki, thanks for the link. It might be worth mentioning it in the readme.

Can the formatter's behaviour be tweaked similarly to the linter? One style that seems a bit strange that isn't from the style guide is the way that chained functions calls get wrapped over multiple lines. ie
```gdscript
foo()
. call()
. call()
. call()
```
While the style guide doesn't have an example of this exactly, it suggests [Use 2 indent levels to distinguish continuation lines from regular code blocks.](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#indentation) so I would expect it to look more like
```gdscript
foo()
		.call()
		.call()
		.call()
```
(this doesn't look so bad in practice, github is using 8-space tabs for some reason)

**Comment by Scony** [comment]
> I wasn't aware of the wiki, thanks for the link. It might be worth mentioning it in the readme.
> 
> Can the formatter's behaviour be tweaked similarly to the linter? One style that seems a bit strange that isn't from the style guide is the way that chained functions calls get wrapped over multiple lines. ie
> 
> ```gdscript
> foo()
> . call()
> . call()
> . call()
> ```
> 
> While the style guide doesn't have an example of this exactly, it suggests [Use 2 indent levels to distinguish continuation lines from regular code blocks.](https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html#indentation) so I would expect it to look more like
> 
> ```gdscript
> foo()
> 		.call()
> 		.call()
> 		.call()
> ```
> 
> (this doesn't look so bad in practice, github is using 8-space tabs for some reason)

Here, formatter is motivated by python's `black` formatter. Also, I think the first example is more readable (assuming fixed width font is used in the editor).

**Comment by evestroud** [comment]
It's not in the style guide, but prefacing unused variable names with an underscore _is_ the recommendation in the LSP warning message as the OP noted, which does suggest official support for this convention. [Here's the warning in the LSP source code.](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_warning.cpp#L49)

If using the 'Return Value Discarded' warning in the LSP you can wind up in a situation where you want to assign the output of something like `CharacterBody2D.move_and_slide()` to an unused variable for use later in development, but the linter says the naming convention recommended by the GDScript LSP is invalid.

**Comment by Scony** [comment]
> It's not in the style guide, but prefacing unused variable names with an underscore _is_ the recommendation in the LSP warning message as the OP noted, which does suggest official support for this convention. [Here's the warning in the LSP source code.](https://github.com/godotengine/godot/blob/master/modules/gdscript/gdscript_warning.cpp#L49)
> 
> If using the 'Return Value Discarded' warning in the LSP you can wind up in a situation where you want to assign the output of something like `CharacterBody2D.move_and_slide()` to an unused variable for use later in development, but the linter says the naming convention recommended by the GDScript LSP is invalid.

Well, IMO having an unused local variable prefixed with `_` is a code smell. It's a dead code that in Godot may even impact the runtime performance (as there are no LLVM-level-like optimizations for GDScript so far). Moreover, it's very common in GDScript to have class variables prefixed with `_` to denote they are "private". Allowing local variables to be also prefixed with `_` would lead to less readability in blocks like:

```
_xyz = _abc(1,2,3) + _foo
var _qwe = "unused" + str(_foo)
# etc.
```
Therefore I think the current default is reasonable.

**Comment by Jack-023** [comment]
> Here, formatter is motivated by python's `black` formatter. Also, I think the first example is more readable (assuming fixed width font is used in the editor).

I personally think it looks a bit weird, I think it is mostly the space after the .
Are the non-standard style choices documented anywhere? It would help to avoid raising issues for things that may be intentional.

> Well, IMO having an unused local variable prefixed with _ is a code smell. It's a dead code that in Godot may even impact the runtime performance (as there are no LLVM-level-like optimizations for GDScript so far).

I see where you are coming from and I somewhat agree. The main problem then becomes the fact that gdscript doesn't provide a way to ignore warnings over a range, only for a single line. This results in pretty clunky workarounds like this snippet from my codebase:
```gdscript
@warning_ignore("return_value_discarded")
tween.tween_property(self, ^"scale", Vector2.ONE * scale_factor, 1)
var x_offset := randf_range(-10, 10)
@warning_ignore("return_value_discarded")
tween.tween_property(self, ^"position", Vector2(x_offset, -15), 1)
@warning_ignore("return_value_discarded")
tween.chain().tween_property(self, ^"modulate:a", 0, 0.5)
@warning_ignore("return_value_discarded")
tween.tween_callback(queue_free)
```

This is more of an gdscript issue though.
