### ISSUE TITLE
gdlint: position of static vars

### ISSUE THREAD

**Issue by dekaravanhoc** [Scony/godot-gdscript-toolkit#331]
Hey,

great tool. 
I would like to know, why are static vars below every other variable declaration? There does not seem an official statement on this in the docs and I feel they should be after constants. As you can access static vars in vars, but not the other way around. So the declaration order should reflect that?

Thanks! :)

**Comment by Scony** [comment]
Good point, perhaps this is a bug - I need to check it.

**Comment by dekaravanhoc** [comment]
Thanks. 
It seems to behave correctly regarding the definition [here](https://github.com/Scony/godot-gdscript-toolkit/blob/e204a49cf9c1a863ae5bcc08eb140930f7f830d5/gdtoolkit/linter/__init__.py#L72)
