### ISSUE TITLE
Using master as version 4.3.2

### ISSUE THREAD

**Issue by tuimz** [Scony/godot-gdscript-toolkit#335]
Hi,

I was using master (pip3 install git+https://github.com/Scony/godot-gdscript-toolkit.git) but when I freeze the dependencies to a file it says `gdtoolkit==4.3.2` and this version is not tagged/released yet.

Could you release this?

I am using master specifically for the `super._ready()` calls

**Comment by Scony** [comment]
So far I've been reluctant to release as I've been gathering feedback on multiline lambdas support. However, I think if nothing new pops up in the upcoming few days this can be done. Please ping me here if the release won't happen in few (let's say 5) days.

**Comment by Scony** [comment]
Done.
