### ISSUE TITLE
None in class-definitions-order error message

### ISSUE THREAD

**Issue by DanielChabrowski** [Scony/godot-gdscript-toolkit#343]
siema,
long time no see :)

Running gdlint on a following MRE:
```
func _ready():
	pass

var x = 0
```

yields:
```
t.gd:4: Error: Definition out of order in None (class-definitions-order)
```

As the first time user of gdlint it was rather surprising and confusing to see None in the error message, thinking it came somewhere from my code. From what I can see, it used to say "global scope" before changes in the `78496d74a0e440a5cec25ab5e30d8d191baa0f05`. Didn't find anything in the issue tracker or in wiki so reporting just in case this wasn't an intended change.

**Comment by Scony** [comment]
@manuq yeah, sorry about the delay, will do this in upcoming days
