### ISSUE TITLE
emacs module for formatter

### ISSUE THREAD

**Issue by Scony** [Scony/godot-gdscript-toolkit#35]

**Comment by NathanLovato** [comment]
You use Emacs too? I'll try to hook it to our GDScript mode when it's ready to test: https://github.com/GDQuest/emacs-gdscript-mode

**Comment by Scony** [comment]
Yes - and even tho I use it for 10 years, I dunno much elisp. Yet I'll try to provide simple macro for buffer formatting. Should be easy to integrate to your module eventually :)
