### ISSUE TITLE
Add a keyword to detect virtual functions

### ISSUE THREAD

**Issue by NathanLovato** [Scony/godot-gdscript-toolkit#45]
Virtual and private methods start with one underscore by convention in Godot. Virtual methods should be documented while private methods shouldn't appear in the class reference.

We should have a way to tag or add a keyword to functions so they are treated as virtual

**Comment by Scony** [comment]
Do you have anything more specific in mind? Some sort of python-like-annotations or specific keyword?

**Comment by NathanLovato** [comment]
Sorry, I'm making git issues from the command line, I must've called hub from the clone of this repo!
