### ISSUE TITLE
Wildcards don't work on Windows

### ISSUE THREAD

**Issue by Awkor** [Scony/godot-gdscript-toolkit#51]
```
E:\>gdformat *.gd
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python37-32\Scripts\gdformat-script.py", line 11, in <module>
    load_entry_point('gdtoolkit==3.2.4', 'console_scripts', 'gdformat')()
  File "c:\program files (x86)\python37-32\lib\site-packages\gdtoolkit\formatter\__main__.py", line 91, in main
    with open(file_path, "r+") as fh:
OSError: [Errno 22] Invalid argument: '*.gd'
```
This is because the Windows console doesn't expand wildcards, but passes them directly to the script.

I'm no Python expert, but looking around I read that the [glob](https://docs.python.org/3.7/library/glob.html) module could be used to solve this issue.

I'll also use this issue to thank the developer and contributors of this amazing project!

**Comment by Scony** [comment]
Thanks! This is good idea.

**Comment by Scony** [comment]
As I'm unable to fix and test it on Windows as well as there are no volunteers to help, I'm closing it as it probably won't ever get fixed. Sorry.
