### ISSUE TITLE
Formatter VSCode extension

### ISSUE THREAD

**Issue by Razoric480** [Scony/godot-gdscript-toolkit#55]
I coded up a first pass at a VSCode extension that uses the formatter over on [this fork](https://github.com/Razoric480/godot-gdscript-toolkit/tree/vscode-plugin).

Would adding this to the official /editor-plugins/ folder be of interest (that is, PRed in) as something you'd want to maintain (Azure account, publishing token, etc,) once it's finished, or should I stick to maintaining it on its own separate repo and act as the extension publisher?

**Comment by Scony** [comment]
Well, adding this extension under `/editor-plugins/` is very welcome. It is especially handy from the user's perspective, as everything is in one place. However, I'm not VSCode user, so it would be better if you keep maintaining it and acting as an extension publisher. If you can do it as a contributor (via PRs) that would be perfect. I will gladly merge anything that goes into `/editor-plugins/vscode`.

So, it's up to you :) In case you want to maintain your own repo (for reasons such as versioning, CI, or so) I will just paste a link to your repo, so people can easily find it.

**Comment by Razoric480** [comment]
I don't think I need the repo itself to publish to the extension marketplace, so I'd be happy to put it up with your repo, so it'll be near the code it uses, and we can gather issues in one place.
