### ISSUE TITLE
Dropping support for Python 3.6?

### ISSUE THREAD

**Issue by NathanLovato** [Scony/godot-gdscript-toolkit#6]
I saw in the code you wanted to use features from Python 3.7. Is there a particular reason you want to support several versions of Python? Is it for servers or something that'd be on LTS and couldn't upgrade to py 3.7/3.8? 

This would give us access to the `breakpoint()` function, dataclasses, but you could also remove boilerplate code in the linter using module attributes and the `__dir__` special function: I think that we can avoid having to maintain the linter features list by hand easily that way.

**Comment by Scony** [comment]
Well I just wanted to reach more potential users. But actually since Debian is on 3.7 (just checked it) I think it's reasonable to give up 3.6.
