### ISSUE TITLE
Improve startup speed by caching the lark trees to disk

### ISSUE THREAD

**Issue by NathanLovato** [Scony/godot-gdscript-toolkit#61]
I got started on that already, using python's pickle module to write the parser objects as binary after computing them for the first time.

It's a bit crude right now but startup is near-instant from the second run of gdformat onwards here, with an SSD drive.

I just need to figure out where to save the cache files depending of the OS, any suggestion for that? On unix it's $HOME/.cache, but how about windows?

```py
    @cached_property
    def _parser_with_metadata(self) -> Tree:
        tree: Tree = None
        filename: str = "parser_with_metadata"
        filepath: str = os.path.join(self._cache_dirpath, filename)
        if os.path.exists(filepath):
            tree = self.load(filepath)
            print("loaded tree object {}".format(tree))
        else:
            tree = Lark.open(
                os.path.join(self._directory, "gdscript.lark"),
                postlex=Indenter(),
                parser="lalr",
                start="start",
                propagate_positions=True,
                maybe_placeholders=False,
            )
            self.save(tree, filename)
        return tree


    def save(self, parser: Tree, filename: str) -> None:
        """Serializes the Lark parser and saves it to the disk."""
        if not os.path.exists(self._cache_dirpath):
            os.makedirs(self._cache_dirpath)
        path: str = os.path.join(self._cache_dirpath, filename)
        print("Saving to path {}".format(path))
        pickle.dump(parser, open(path, "wb"), protocol=4)

    def load(self, filename: str) -> Tree:
        """Loads the Lark parser from the disk and deserializes it."""
        path: str = os.path.join(self._cache_dirpath, filename)
        print("Loading from {}".format(path))
        return pickle.load(open(path, "rb"))
```

**Comment by Scony** [comment]
Take a look at https://stackoverflow.com/questions/4028904/how-to-get-the-home-directory-in-python 
btw. I'd suggest to use gdtoolkit version as a file name, so if someone upgrades module from, say 3.2.x to 3.2.y the cache will be recalculated :)

**Comment by NathanLovato** [comment]
I'm already using expanduser, but I'm not sure what's the rule for cache on Windows. I would guess it's  "~/AppData/Local", but is this true of every Windows version? Also, is it the same on mac?

Surprisingly enough, I didn't find a clear cut answer as to where we should be saving files.

> I'd suggest to use gdtoolkit version as a file name, so if someone upgrades module from, say 3.2.x to 3.2.y the cache will be recalculated :)

Makes sense!

**Comment by NathanLovato** [comment]
Actually, I can't get pickle to work. While it saves the lark parsers without issue, loading them exceeds the recursion limit:

```
RecursionError: maximum recursion depth exceeded
```

I've raised the max recursion limit as high as I could on my system and it still won't work.

**Comment by NathanLovato** [comment]
I don't know what I did earlier, I had maybe broken the formatter and was returning an empty tree or something, the program seemed to run instantly.

While it's possible to raise the recursion limit of the system, you need root access to do so, so it's not a solution for this project. I researched these issues with pickle and it seems there's no other way around it. So it may not work.

At least I refactored the code and prepared something to [de]serialize the lark object. I'll look into the gpl 2 code that you linked.

**Comment by NathanLovato** [comment]
Okay so it seems lark has its own code to serialize and deserialize trees. It's undocumented but reading the source code and the example you linked to, I'll try to make it work.

**Comment by Scony** [comment]
Ok
