### ISSUE TITLE
Formatter indents comments to code block level

### ISSUE THREAD

**Issue by kkga** [Scony/godot-gdscript-toolkit#65]
It might be useful to have an option flag for ignoring comments in the `gdformat` program. More often than not, indenting comments results in an undesired formatting:

<img width="1341" alt="image" src="https://user-images.githubusercontent.com/1460122/75370862-d94a6b00-58d6-11ea-89bf-a671bbcd1a3a.png">

**Comment by NathanLovato** [comment]
It's true that Godot's built-in comment line feature adds the `#` at the start of the line, before the indents. To me, it's weird that it does that in the first place, but it can't be helped right now I guess.

The formatter could provide an option to preserve the existing indent for comments.

**Comment by NathanLovato** [comment]
Note that the way gdformat treats comments is in line with the official guideline, you're supposed to have one space between the # and the start of the comment for explanations, no space if you're disabling code. Well, it's a bit of a weird one.

I'd suggest changing the way the gdscript editor comments lines as well, it's unlike any other code editor I've seen and used.

**Comment by Scony** [comment]
I had no idea Godot's editor works this way. Anyway 

> changing the way the gdscript editor comments lines

is a good idea. But till then my proposition would be as follows:
*if block comment has indentation level 0, keep it at 0. Work as usual otherwise.*
