### ISSUE TITLE
Formatter mishandles single line if/for

### ISSUE THREAD

**Issue by x2f** [Scony/godot-gdscript-toolkit#67]
In gdformat 3.2.5:

Code like this:
```
if condition: action()
another_action()
```
Will become
```
if condition:
    action()
    another_action()
```

**Comment by NathanLovato** [comment]
While that indeed changes your original code, single-line condition blocks are not idiomatic in GDScript and not recommended. The official style, which gdformat follows, requires you to use blocks for everything.

**Comment by x2f** [comment]
I definitely agree, and used the opportunity to go through the code base and change this (by hand). But as it is, gdformat breaks code: if someone mistakenly writes a single liner if/for, the formatter could silently introduce a bug...

**Comment by Scony** [comment]
Yes, although the inline syntax is not recommended there is no excuse for gdtoolkit to misbehave :) It's a bug in grammar, I'll fix it.
