### ISSUE TITLE
GDFormat throws exception when encountering ^=, <<= or >>= operators

### ISSUE THREAD

**Issue by Razoric480** [Scony/godot-gdscript-toolkit#74]
See title.

For reference, ^ is inclusive or (XOR.) It seems &= and |= are both implemented and recognized, and just ^= is missing.

\>> and << are bitwise shifts.

```
var hash_32 = 123456789
hash_32 ^= PRIME_1
hash_32 >>= 32
hash_32 <<= 16
```

**Comment by Calinou** [comment]
I can confirm this with gdlint 3.2.6.

**Comment by Scony** [comment]
Right! Thank you both. I've probably used [this godot docs page](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_basics.html) and hence the mistake.

I'll provide the fix soon. Btw. @Calinou you're a frequent contributor to docs - it may be worth updating docs section mentioned above.
