### ISSUE TITLE
Allow recursively formatting files

### ISSUE THREAD

**Issue by aaronfranke** [Scony/godot-gdscript-toolkit#75]
Instead of `gdformat file.gd`, I would like to do this for all GDScript files at once. It would be nice to have a recursive option, something like `gdformat -R` which would recursively format all files in the current working directory.

**Comment by Scony** [comment]
Would it be okay if instead of `working directory` user would be obligated to pass directories as arguments? In your case you could do `gdformat . -R` to format current dir

**Comment by aaronfranke** [comment]
Yes, either works. Actually, if running `gdformat .` can detect that it's a directory, perhaps there is no need for `-R` since it's obviously not a file?

**Comment by Scony** [comment]
I'll figure something out. For temporary workaround (in case you use linux) go for:
```
find -name '*.gd' | xargs gdformat
```

**Comment by NathanLovato** [comment]
Use find -exec for that:

find -name '*.gd' -exec gdformat "{}" ";" 

It should prevent errors if you have whitespace in your paths.

In fish, you also have gdformat **.gd
