### ISSUE TITLE
Format quotes

### ISSUE THREAD

**Issue by GammaGames** [Scony/godot-gdscript-toolkit#77]
Taken from the documentation ([source](https://docs.godotengine.org/en/stable/getting_started/scripting/gdscript/gdscript_styleguide.html#quotes)):

## Quotes
Use double quotes unless single quotes make it possible to escape fewer characters in a given string

I think it would be nice to auto-format string quotes to be `"` as well, maybe not enable by default but enabled with a flag?

**Comment by Scony** [comment]
that's a good point. Originally I was even going to do that but apparently I forgot. I'm trying to follow how black works for python and it transforms `'` to `"` without flags, so I think that's the way to do it.
