### ISSUE TITLE
Arch Linux PKGBUILD

### ISSUE THREAD

**Issue by clofresh** [Scony/godot-gdscript-toolkit#88]
Hello, I noticed there wasn't an Arch Linux AUR package for gdtoolkit, so I created a PKGBUILD:

```
pkgbase='gdtoolkit'
pkgname="python-${pkgbase}"
pkgver='3.2.7'
pkgrel='1'
pkgdesc='Independent set of tools for working with GDScript - parser, linter and formatter'
arch=('any')
url="https://github.com/Scony/godot-gdscript-toolkit"
depends=('python-lark-parser' 'python-docopt' 'python-pyaml')
makedepends=('python' 'python-setuptools')
license=('MIT')
source=("https://pypi.io/packages/source/${pkgbase:0:1}/${pkgbase}/${pkgbase}-${pkgver}.tar.gz")
sha256sums=('63736504a2a61de2fde9d6c7b1a6888c790b7dce0be64eac78c487124376e3e0')

package() {
  cd "${srcdir}/${pkgbase}-${pkgver}"
  python setup.py install -O1 --root="${pkgdir}"
}
```

I'm not able to keep the package up to date though, so I was wondering if you'd want to be the maintainer.

**Comment by Scony** [comment]
I don't have experience with maintaining AUR packages but will give it a try. Thanks!

**Comment by Scony** [comment]
I've been thinking about this and I think I'll not have time to maintain such a package. @clofresh if you like, feel free to create/maintain one for AUR. I'd appreciate it :)
