### ISSUE TITLE
Could we use static type hints?

### ISSUE THREAD

**Issue by NathanLovato** [Scony/godot-gdscript-toolkit#9]
Python 3.7 and 3.8 now support type hints pretty well, reporting on quite a few errors that linters won't catch otherwise. Also, they make the code more self-documenting. There are functions for which type hints could help a lot when exploring the code, like

```py
def parse(code, gather_metadata=False):
```

vs

```py
def parse(code: str = "", gather_metadata: bool = False) -> Tree:
```

In general, without type hints, it takes more time than it could to figure out how the code works for a newcomer like me.

Would you be okay with using type hints?

**Comment by Scony** [comment]
Yes, sure. Code is much more readable and less error prone. Good idea.

**Comment by NathanLovato** [comment]
I started adding them, will push a PR in a moment.

**Comment by NathanLovato** [comment]
I added type hints to the linter tonight, but it makes the tests run insanely slow: 1:30 to run all tests. Any idea why?
