### ISSUE TITLE
ImportError: No module named gdtoolkit.formatter

### ISSUE THREAD

**Issue by jsbeckr** [Scony/godot-gdscript-toolkit#90]
Hi,

have installed the VS Code extension and installed gdtoolkit via `pip3 install gdtoolkit`. But I'm getting an error `ImportError: No module named gdtoolkit.formatter` in VS Code.

macOS Catalina
VS Code: 1.47.3
GDScript Formatter: 1.2.1
gdtoolkit: 3.2.7 

I can run `gdformat ...` just fine from my terminal.

Am I missing something?

Thank you :)

**Comment by Scony** [comment]
hey, maybe your VSCode uses python2? Or you've installed gdtoolkit for python2?

Could you please show the output of the following commands:
```
python3 -m gdtoolkit.formatter
python2 -m gdtoolkit.formatter
```
?

**Comment by jsbeckr** [comment]
I installed it with `pip3`

![image](https://user-images.githubusercontent.com/147412/89947741-405da100-dc25-11ea-9bd7-c14eed95bd83.png)

**Comment by Scony** [comment]
Mhmm... maybe @Razoric480 has any idea

**Comment by Razoric480** [comment]
It's possible that Visual Studio Code it's using the wrong version of python. #72 introduced a way of using the path from the Python Path variable. Try going into VSCode's settings (File -> Preferences -> Settings) and searching for "Python Path". Scroll down to the Python Path variable and try replacing what's in there with python3, then try VSCode's format again.

**Comment by jsbeckr** [comment]
@Razoric480 Yes that was it! Thank you very much!

Maybe worth mentioning in the Readme?

**Comment by Scony** [comment]
That's a good idea.
