### ISSUE TITLE
Error while formatting - ValueError: unsupported pickle protocol: 5

### ISSUE THREAD

**Issue by vickylance** [Scony/godot-gdscript-toolkit#93]
I am getting the below error when I try to run the formatter using the below command.

```
/Users/vickylance/Library/Python/3.7/bin/gdformat ./**/*.gd
```

![image](https://user-images.githubusercontent.com/5861833/90285554-c7af4c80-de91-11ea-9769-285c373429cb.png)

**Comment by Scony** [comment]
Is it Windows or Linux?

**Comment by fire** [comment]
I can reproduce on Windows too.

**Comment by vickylance** [comment]
@Scony  it was on Mac btw
