### ISSUE TITLE
GDformat put line breaks inside a preload statement

### ISSUE THREAD

**Issue by idJoca** [Scony/godot-gdscript-toolkit#94]
## Hello There!

As of GDformat 3.2.7,
when a preload line is too long, 2 line breaks are placed at it, one at the start and the other at the end. Ending up like this:

```gdscript
const scene = preload(
	"res://foo/bar/scene.tscn" # Suppose this is a long line
)
```
Which, unfortunately, triggers the Parser, resulting at the following error:
![image](https://user-images.githubusercontent.com/37230465/93000507-48984d00-f4ff-11ea-9b80-ba22432f9148.png)
>  FILE_PATH - Parse Error: Error parsing expression, misplaced: '\n'
 modules/gdscript/gdscript.cpp:599 - Method failed. Returning: ERR_PARSE_ERROR

**Comment by Scony** [comment]
It's already fixed on `master` in #79. You can install master's version via `pip3 install git+https://github.com/Scony/godot-gdscript-toolkit.git`
