### ISSUE TITLE
Error while formating document in VS Code

### ISSUE THREAD

**Issue by F0rsaken** [Scony/godot-gdscript-toolkit#95]
I installed extension in VS Code and GDTollkit with pip3. Formating with GDToolkit works in terminal, but when trying to run in VS Code, it throws an error: `ImportError: No module named gdtoolkit.formatter`.

I work on macOS 10.15.5

**Comment by Scony** [comment]
`gdtoolkit` is not being tested on MacOS, so it may be anything. Personally I'm unable to test/help w/ MacOS. @Razoric480 do you have Mac?

**Comment by Razoric480** [comment]
I do *blows dust off of it* I'll take a look.

**Comment by Razoric480** [comment]
@F0rsaken Okay, make sure of the following:

1. Open Code -> Preferences
1. Search for Python Path
1. Make sure it's set to `python3` and not `python`

The default `python` is assigned to python 2, but you installed it with pip3 (and GDtoolkit requires python 3.) So when VSCode tries to use the python runtime, it's running it with python2 and is unable to find GDToolkit, and tells you as much.

**Comment by F0rsaken** [comment]
OMG! Love you guys! It worked! ❤️ 

I'm using `ZSH` in my terminal and have `python` as an alias to `python3` but VS Code probably uses `bash` and that's why the problem occured.

I think it would be great to mention it in `Known issues` section of docs. I can contribute to that, if you think the same.

**Comment by Razoric480** [comment]
Sure, go ahead.

**Comment by Scony** [comment]
Thanks! Btw. I lied about MacOS testing - our Travis CI regression test suite runs on Mac as well. We're safe :)
